import type { Lesson } from "@/game/lessons";
import type { Lang } from "./messages";

type Copy = { title: string; lead: string; points: string[]; hint: string; success: string };

function L(title: string, lead: string, points: string[], hint: string, success = ""): Copy {
  return { title, lead, points, hint, success };
}

const en: Record<string, Copy> = {
  goal: L("The goal", "Chess is a fight between two armies on 64 squares. You do not need to capture every piece — only to leave the enemy king with no escape.", ["The board has files a–h and ranks 1–8. Each side starts with 8 pawns, 2 rooks, 2 knights, 2 bishops, 1 queen and 1 king.", "White moves first. Then the sides alternate, one move each.", "You win by checkmate: the enemy king is attacked and no legal move escapes.", "The king is never captured. The game stops at checkmate.", "The game is drawn by stalemate, repetition, insufficient material, the 50-move rule, or agreement."], "When you have read this, go to the next lesson."),
  controls: L("How to move", "On this board a move is two taps: choose a piece, then choose a square.", ["Tap a piece of the side to move. Legal squares light up.", "A dot is an empty square. A ring is an enemy piece — tap it to capture.", "Tap another friendly piece to change your choice. Tap an illegal square to cancel.", "Drag to orbit. The arrows pan the camera. + zooms to the selected piece, − zooms out, and the square frames the whole board.", "Try any legal move for White."], "Choose a white piece, then tap a lit square.", "Correct. A lit square is legal. An unlit square cannot be reached."),
  pawn: L("The pawn", "The pawn is slow and only moves forward, but it is the only piece that captures in a different direction from the way it moves.", ["It moves one square straight ahead if that square is empty. It cannot move backward.", "From its starting rank it may move two squares if both squares ahead are empty.", "It captures one square diagonally forward, never straight ahead.", "On the last rank it must promote to another piece.", "The white pawn is on e4. Capture the black pawn on d5."], "Tap the white pawn, then tap d5.", "Pawns capture diagonally. Moving straight to e5 would not take the piece on the diagonal."),
  rook: L("The rook", "The rook moves along ranks and files, as far as it wants, if the path is clear.", ["It moves sideways or straight, never diagonally, and it cannot jump.", "It may stop on an empty square or on an enemy piece to capture it. It cannot land on a friendly piece.", "A rook is strongest on an open file — a file with no pawns of either side.", "Move the rook from a1 all the way up the a-file to a8."], "Tap the rook on a1, then tap a8.", "The rook travels the whole a-file because nothing stands between."),
  knight: L("The knight", "The knight is the only piece that jumps. Its move is always an L.", ["Two squares one way, then one square sideways. Or one square, then two.", "It jumps over friends and enemies. An empty destination is a move; an enemy there is a capture.", "Every move changes the color of its square: from a dark square it lands on a light one, and the reverse.", "Move the knight from b1 to c3."], "Tap the knight on b1, then tap c3.", "Two squares up and one to the right — that is the L. The knight needs no clear path."),
  bishop: L("The bishop", "The bishop moves only diagonally and stays on one square color for the whole game.", ["It may go any distance diagonally, but it cannot jump.", "A bishop that starts on a dark square can never reach a light square. The two bishops of one side therefore watch different colors.", "This bishop is on c1, a dark square. g5 is also dark, on the same diagonal.", "Move the bishop to g5."], "Tap the bishop on c1, then tap g5.", "The bishop kept its square color. It never switches to a light square."),
  queen: L("The queen", "The queen moves like a rook and a bishop together: sideways, straight, or diagonally.", ["Any distance, but it cannot jump.", "The queen is the strongest piece because it can switch between both directions. Losing it usually loses the position.", "From d1 the queen can move like a rook along the file or like a bishop on a diagonal.", "Move the queen along the diagonal to h5."], "Tap the queen on d1, then tap h5.", "A long diagonal. The queen could also have gone straight to d8."),
  check: L("The king and check", "The king moves slowly, only one square at a time, and it may never step into danger.", ["The king moves one square in any direction: sideways, straight, or diagonally.", "It may not move onto a square attacked by the enemy, and it may not stand next to the enemy king.", "Check means the king is attacked. You must escape at once: move the king, block the line, or capture the checking piece.", "The black rook checks the white king along rank 1. Move the king out of check."], "The king cannot stay on rank 1. Step one square upward.", "The king left the rank the rook controls. Staying there would be illegal."),
  mate: L("Checkmate", "Checkmate is a check the king cannot leave, cannot block, and cannot answer by capturing the checking piece.", ["Unlike an ordinary check, the other side has no legal move at all.", "The king is not taken off the board. The game ends, and the mating side wins.", "This is the scholar's mate: the queen is on h5 and the bishop on c4 looks at f7.", "Capture the pawn on f7 with the queen."], "Tap the queen on h5, then tap f7.", "The queen on f7 is protected by the bishop on c4. The black king cannot take it, cannot block, and has no flight square."),
  draw: L("Draws and stalemate", "Not every trapped king is a win. If the side to move has no legal move and is not in check, the game is drawn — that is stalemate.", ["It is Black's turn. The king on a8 is not in check, but a7, b7 and b8 are all controlled by the white queen. Black has no move.", "That is stalemate: a draw, not a loss for Black. Driving the king into the corner without giving check can throw away a win.", "A draw also happens when the same position repeats three times, after 50 moves with no capture or pawn move, when neither side has enough material to mate, or when a draw offer is accepted.", "King versus king, king and knight, or king and bishop cannot force checkmate."], "This position is already drawn. Continue to learn castling."),
  castle: L("Castling", "Castling is the only move that moves two pieces at once: the king hides in the corner and a rook comes out.", ["The king moves two squares toward a rook. The rook jumps over the king and lands on the square beside it.", "For White, the kingside on the right is short castling. The queenside on the left is long castling.", "You may castle only if that king and rook have not moved, the squares between them are empty, the king is not in check, and the king does not cross or land on an attacked square.", "Each side castles only once. Castle kingside: move the king from e1 to g1."], "Tap the king on e1, then tap g1. The rook on h1 jumps to f1 by itself.", "The king goes to g1 and the rook to f1. That is one move, not two."),
  passant: L("En passant", "If an enemy pawn has just jumped two squares and landed beside your pawn, you may capture it as if it had moved only one.", ["The black pawn just jumped from d7 to d5, beside the white pawn on e5.", "White may capture diagonally to d6. The black pawn on d5 disappears, even though you land on d6.", "The right lasts only for the immediate next move. Any other move loses it.", "Capture en passant: the pawn on e5 goes to d6."], "Tap the white pawn on e5, then tap d6.", "The black pawn is captured even though it does not stand on the square you moved to. This is the only capture that lands off the captured piece."),
  promote: L("Promotion", "A pawn that reaches the last rank is no longer a pawn. You must turn it into a queen, rook, bishop, or knight.", ["White promotes on rank 8. Black promotes on rank 1. The change is required and happens in the same move.", "Most of the time choose a queen, because it covers the most directions.", "Sometimes a knight is stronger, if its jump checks the enemy king at once.", "Push the pawn from e7 to e8 and promote it to a queen."], "Tap the pawn on e7, tap e8, then choose Queen.", "The pawn became a queen. A pawn on the last rank often changes the whole game."),
};

const zh: Record<string, Copy> = {
  goal: L("目标", "国际象棋是双方在 64 格上的对战。不必吃光所有棋子，只要让对方的王无路可逃。", ["棋盘有 a–h 八列、1–8 八行。每方开局有 8 兵、2 车、2 马、2 象、1 后、1 王。", "白方先走，然后双方轮流，每次一步。", "将杀即胜：对方的王正被攻击，且没有任何合法着法能逃脱。", "王永远不会被吃掉。将杀时对局立刻结束。", "逼和、重复局面、子力不足、五十回合，或双方同意，都是和棋。"], "读完就进入下一课。"),
  controls: L("怎样走棋", "在这张棋盘上，一步棋是两次点按：先选棋子，再选格子。", ["点按轮到一方的棋子，能去的格子会亮起。", "圆点是空格。圆环是敌子 — 点它就是吃子。", "点另一枚己方棋子可改选。点不合法的格子则取消。", "拖动旋转视角。箭头移动镜头。+ 拉近所选棋子，− 拉远，方块回到整盘。", "试着为白方走任意合法的一步。"], "选一枚白子，再点一个亮着的格子。", "对了。亮着的格子才能去，不亮就到不了。"),
  pawn: L("兵", "兵走得慢，只能前进，却是唯一吃子方向和前进方向不同的棋子。", ["若正前方一格为空，就直进一格。不能后退。", "在起始行可以一次进两格，但两格都必须空。", "斜前方一格吃子，绝不直吃。", "到达最后一排必须升变。", "白兵在 e4。请吃掉 d5 的黑兵。"], "点白兵，再点 d5。", "兵斜着吃。如果直走 e5，就吃不到斜前方的棋子。"),
  rook: L("车", "车沿横线或直线走，只要路上没有阻挡，多远都可以。", ["横走或直走，不斜走，也不能跳过棋子。", "可停在空格，或停在敌子上把它吃掉。不能停在己方棋子上。", "车在开放线上最强 — 该列双方都没有兵。", "把车从 a1 沿 a 列一直走到 a8。"], "点 a1 的车，再点 a8。", "a 列中间没有棋子，所以车可以走完全程。"),
  knight: L("马", "马是唯一能跳过其他棋子的棋子。它的走法永远是 L 形。", ["先走两格再横一格，或先走一格再横两格。", "可以跳过己方和敌方。落点空则走动，有敌子则吃掉。", "每走一步都换格色：黑格出发就落到白格，反之亦然。", "把马从 b1 走到 c3。"], "点 b1 的马，再点 c3。", "向上两格、向右一格，就是 L。马不需要通路。"),
  bishop: L("象", "象只走斜线，并且整局都待在同一种颜色的格子上。", ["斜走多远都可以，但不能跳过棋子。", "从黑格出发的象永远到不了白格。所以一方的两只象各管一种颜色。", "这只象在 c1，是黑格。g5 也是黑格，在同一条斜线上。", "把象走到 g5。"], "点 c1 的象，再点 g5。", "象守住了自己的格色，永远不会改到白格。"),
  queen: L("后", "后兼有车和象的走法：横、直或斜。", ["多远都可以，但不能跳过棋子。", "后最强，因为它能在两种方向间切换。失去后通常会失去局面。", "从 d1，后可以像车一样直走，或像象一样斜走。", "请沿斜线把后走到 h5。"], "点 d1 的后，再点 h5。", "一条长斜线。后也可以直走到 d8。"),
  check: L("王与将军", "王走得很慢，每次只一格，而且绝不能走进危险。", ["王可以向任何方向走一格：横、直或斜。", "不能走到被敌子攻击的格子，也不能和对方的王相邻。", "将军就是王正被攻击。必须立刻逃脱：移开王、挡住，或吃掉正在将军的棋子。", "黑车沿第 1 行将军白王。请把王走出将军。"], "王不能留在第 1 行。向上走一格。", "王离开了车控制的那一行。留在那里是非法的。"),
  mate: L("将杀", "将杀是这样一种将军：王走不开、挡不住，也不能吃掉正在将军的棋子。", ["和普通将军不同：对方已经没有任何合法着法。", "王不会被拿下棋盘。对局结束，将杀的一方获胜。", "这是学者将杀：后在 h5，象在 c4 看着 f7。", "用后吃掉 f7 的兵。"], "点 h5 的后，再点 f7。", "f7 的后受 c4 的象保护。黑王吃不掉它，挡不住，也没有逃格。"),
  draw: L("和棋与逼和", "不是每个被困住的王都算输。如果轮到的一方没有合法着法，又没有被将军，就是逼和。", ["轮到黑方。a8 的王没有被将军，但 a7、b7、b8 都由白后控制。黑方无子可走。", "这是逼和：和棋，不是黑方输。把王逼到角落却忘了将军，可能丢掉胜局。", "同一局面重复三次、连续 50 步没有吃子或进兵、双方子力不足以将杀，或求和被接受，也都是和棋。", "王对王、王单马、王单象，都无法强迫将杀。"], "这个局面已经和了。下一课学王车易位。"),
  castle: L("王车易位", "王车易位是唯一同时移动两枚棋子的着法：王躲进角落，车出来参战。", ["王向车的方向走两格。车跳过王，停在王旁边。", "对白方来说，右边王翼是短易位，左边后翼是长易位。", "只有王和那只车都没动过、中间格子都空、王没被将军，且王不经过也不停在受攻击的格子上，才能易位。", "每方只能易位一次。请王翼易位：把王从 e1 走到 g1。"], "点 e1 的王，再点 g1。h1 的车会自己跳到 f1。", "王到 g1，车到 f1。这是一步，不是两步。"),
  passant: L("吃过路兵", "如果敌兵刚跳了两格，并停在你的兵旁边，你可以把它当成只走了一格来吃。", ["黑兵刚从 d7 跳到 d5，与 e5 的白兵并排。", "白方可斜吃到 d6。d5 的黑兵消失，尽管你落到的是 d6。", "这个权利只在紧接着的下一步有效。走了别的着法就失去。", "请吃过路兵：e5 的兵走到 d6。"], "点 e5 的白兵，再点 d6。", "黑兵被吃了，尽管它并不站在你落到的格子上。这是唯一落点不在被吃棋子上的吃子。"),
  promote: L("升变", "兵走到最后一排就不再是兵。你必须把它换成后、车、象或马。", ["白方在第 8 行升变，黑方在第 1 行。换子是强制的，并在同一步完成。", "多数时候选后，因为后能走的方向最多。", "有时升马更强，如果马的一跳正好将军。", "把 e7 的兵推到 e8，并升变为后。"], "点 e7 的兵，点 e8，然后选后。", "兵变成了后。一个到达底线的兵常常改变整盘棋。"),
};

const ja: Record<string, Copy> = {
  goal: L("目的", "チェスは64マスの上で二つの軍が戦うゲームです。駒を全部取る必要はありません。相手のキングに逃げ道をなくせば勝ちです。", ["盤には a〜h の8ファイルと 1〜8 の8ランクがあります。開始時は各陣営ポーン8、ルーク2、ナイト2、ビショップ2、クイーン1、キング1です。", "先手は白。その後は交互に1手ずつです。", "チェックメイトで勝ちです。相手のキングが攻撃され、合法手で逃げられません。", "キングは取られません。メイトで対局は止まります。", "ステイルメイト、反復、戦力不足、50手ルール、合意で引き分けです。"], "読んだら次のレッスンへ。"),
  controls: L("指し方", "この盤では、1手は2回のタップです。駒を選び、次にマスを選びます。", ["手番の駒をタップすると、行けるマスが光ります。", "点は空きマス。輪は敵の駒で、タップすると取れます。", "同じ陣営の別の駒をタップすると選び直せます。行けないマスで選択解除です。", "ドラッグで視点を回します。矢印はカメラ移動。+ は選択中の駒へ寄り、− は引き、四角で盤全体です。", "白の合法手をどれか指してみてください。"], "白の駒を選び、光っているマスをタップ。", "正解です。光るマスが合法で、光らないマスには行けません。"),
  pawn: L("ポーン", "ポーンは遅く、前にしか進みません。進む方向と取る方向が違う唯一の駒です。", ["前が空なら1マスまっすぐ進みます。後ろには行けません。", "初期位置からは、前の2マスが両方空なら2マス進めます。", "取るのは斜め前の1マスだけ。まっすぐは取れません。", "最終ランクに着いたら必ず別の駒に昇格します。", "白のポーンは e4 にいます。d5 の黒ポーンを取ってください。"], "白ポーンをタップし、d5 をタップ。", "ポーンは斜めに取ります。まっすぐ e5 では斜めの駒は取れません。"),
  rook: L("ルーク", "ルークはランクとファイルに沿って、道が空いていればどこまでも進めます。", ["横か縦だけ。斜めは不可で、駒を飛べません。", "空きマスで止まるか、敵の駒の上で取ります。味方の上には止まれません。", "オープンファイル、つまり両陣営のポーンがないファイルで最も強いです。", "a1 のルークを a ファイルの端、a8 まで進めてください。"], "a1 のルークをタップし、a8 をタップ。", "間に駒がないので、a ファイルを一気に進めます。"),
  knight: L("ナイト", "ナイトだけが他の駒を飛び越えます。動きは常に L 字です。", ["一方向に2マス、それから横に1マス。または1マスのあと2マス。", "味方の上も敵の上も飛べます。行き先が空きなら移動、敵なら捕獲です。", "動くたびにマスの色が変わります。黒マスから白マスへ、その逆もです。", "ナイトを b1 から c3 へ。"], "b1 のナイトをタップし、c3 をタップ。", "2マス上、1マス右。それが L です。道は空いていなくて構いません。"),
  bishop: L("ビショップ", "ビショップは斜めだけ動き、対局中ずっと同じ色のマスにいます。", ["斜めなら何マスでも。ただし跳べません。", "黒マスから始まったビショップは白マスに行けません。だから2つのビショップは別々の色を見ています。", "このビショップは黒マスの c1 にいます。g5 も同じ斜めの黒マスです。", "g5 へ進めてください。"], "c1 のビショップをタップし、g5 をタップ。", "マスの色は変わりません。白マスには決して移りません。"),
  queen: L("クイーン", "クイーンはルークとビショップを合わせた動きです。横、縦、斜め。", ["距離は自由ですが、跳べません。", "両方向を切り替えられるので最強です。失うと形勢も失いやすいです。", "d1 からは、ルークのように縦にも、ビショップのように斜めにも行けます。", "斜めに h5 へ進めてください。"], "d1 のクイーンをタップし、h5 をタップ。", "長い斜めです。縦に d8 へ行くこともできました。"),
  check: L("キングとチェック", "キングは遅く、1手に1マスだけ。危険なマスには入れません。", ["横、縦、斜め、どの方向にも1マスです。", "敵に攻撃されているマスには行けず、敵キングの隣にも立てません。", "チェックはキングが攻撃されている状態です。すぐに逃げます。キングを動かす、ラインを塞ぐ、またはチェックしている駒を取ります。", "黒のルークが1ランクで白キングをチェックしています。チェックから逃げてください。"], "1ランクには留まれません。1マス上へ。", "ルークが支配するランクから出ました。残ると反則です。"),
  mate: L("チェックメイト", "チェックメイトは、キングが逃げられず、防げず、チェックしている駒も取れないチェックです。", ["普通のチェックと違い、相手に合法手が一つもありません。", "キングは盤から取られません。対局は終わり、メイトした側の勝ちです。", "これは学者のメイトです。クイーンは h5、ビショップは c4 から f7 を見ています。", "クイーンで f7 のポーンを取ってください。"], "h5 のクイーンをタップし、f7 をタップ。", "f7 のクイーンは c4 のビショップに守られています。黒キングは取れず、塞げず、逃げマスもありません。"),
  draw: L("引き分けとステイルメイト", "キングが閉じ込められても、必ず勝ちではありません。手番側に合法手がなく、チェックでもないときは引き分け、つまりステイルメイトです。", ["黒番です。a8 のキングはチェックされていませんが、a7、b7、b8 は白クイーンが支配しています。黒に手がありません。", "これがステイルメイトです。黒の負けではありません。角へ追い込んでもチェックを忘れると、勝ちを逃します。", "同一局面の3回、捕獲もポーン前進もない50手、メイトできない戦力、合意でも引き分けです。", "キング同士、キングとナイト、キングとビショップではメイトを強制できません。"], "この局面はすでに引き分けです。次はキャスリングです。"),
  castle: L("キャスリング", "キャスリングは、一度に2つの駒を動かす唯一の手です。キングが隅へ隠れ、ルークが出てきます。", ["キングはルークの方向へ2マス動きます。ルークはキングを飛び越え、隣に止まります。", "白では右側のキングサイドがショート、左側のクイーンサイドがロングです。", "そのキングとルークが未着手で、間が空き、キングがチェック中でなく、通過も停止も攻撃されたマスでないときだけできます。", "各陣営1回だけ。キングサイドへ：キングを e1 から g1 へ。"], "e1 のキングをタップし、g1 をタップ。h1 のルークは自分で f1 へ跳ねます。", "キングは g1、ルークは f1。これは1手であって2手ではありません。"),
  passant: L("アンパッサン", "敵ポーンがちょうど2マス跳んで自分のポーンの横に止まったとき、1マスだけ進んだものとして取れます。", ["黒ポーンは d7 から d5 へ跳び、e5 の白ポーンと横並びです。", "白は斜めに d6 へ取れます。着地は d6 でも、d5 の黒ポーンは消えます。", "この権利は直後の1手だけです。別の手を指すと失います。", "アンパッサンしてください。e5 のポーンを d6 へ。"], "e5 の白ポーンをタップし、d6 をタップ。", "着地したマスにいなくても黒ポーンは取られます。取った駒のマス以外に着地する唯一の捕獲です。"),
  promote: L("プロモーション", "最終ランクに着いたポーンは、もうポーンではありません。クイーン、ルーク、ビショップ、ナイトのどれかに必ず変えます。", ["白は8ランク、黒は1ランクです。変更は必須で、同じ手の中で起きます。", "多くの場合はクイーンです。最も多くの方向に動けるからです。", "ナイトの跳躍がすぐチェックになるときは、ナイトの方が強いこともあります。", "e7 のポーンを e8 へ進め、クイーンに昇格させてください。"], "e7 のポーンをタップし、e8 をタップしてからクイーンを選ぶ。", "ポーンはクイーンになりました。最終ランクのポーンは局面を大きく変えます。"),
};

const ko: Record<string, Copy> = {
  goal: L("목표", "체스는 64칸 위에서 두 군대가 싸우는 게임입니다. 기물을 다 잡을 필요는 없고, 상대 킹이 도망칠 곳이 없으면 이깁니다.", ["보드는 a–h 파일과 1–8 랭크입니다. 각자 폰 8, 룩 2, 나이트 2, 비숍 2, 퀸 1, 킹 1로 시작합니다.", "백이 먼저 두고, 그다음 한 수씩 번갈아 둡니다.", "체크메이트로 이깁니다. 상대 킹이 공격받고 빠져나갈 합법적인 수가 없습니다.", "킹은 잡히지 않습니다. 메이트가 되면 대국은 멈춥니다.", "스테일메이트, 반복, 기물 부족, 50수 규칙, 합의는 무승부입니다."], "다 읽었으면 다음 레슨으로."),
  controls: L("두는 방법", "이 보드에서 한 수는 두 번 누르는 것입니다. 기물을 고르고, 칸을 고릅니다.", ["둘 차례의 기물을 누르면 갈 수 있는 칸이 빛납니다.", "점은 빈 칸, 고리는 상대 기물입니다. 고리를 누르면 잡습니다.", "같은 편 다른 기물을 누르면 선택을 바꿉니다. 불가능한 칸은 선택을 취소합니다.", "끌어 시점을 돌립니다. 화살표는 카메라. +는 선택한 기물에 가까이, −는 멀리, 네모는 보드 전체입니다.", "백의 합법적인 수를 아무거나 두어 보세요."], "흰 기물을 고른 뒤 빛나는 칸을 누르세요.", "맞습니다. 빛나는 칸만 갈 수 있습니다."),
  pawn: L("폰", "폰은 느리고 앞으로만 갑니다. 움직이는 방향과 잡는 방향이 다른 유일한 기물입니다.", ["앞칸이 비어 있으면 한 칸 직진합니다. 뒤로 갈 수 없습니다.", "시작 랭크에서는 앞의 두 칸이 모두 비면 두 칸 갈 수 있습니다.", "잡을 때는 앞 대각선 한 칸입니다. 정면은 잡지 못합니다.", "마지막 랭크에 가면 반드시 다른 기물로 바뀝니다.", "흰 폰이 e4에 있습니다. d5의 검은 폰을 잡으세요."], "흰 폰을 누르고 d5를 누르세요.", "폰은 대각선으로 잡습니다. e5로 직진하면 대각선의 기물을 못 잡습니다."),
  rook: L("룩", "룩은 가로와 세로로, 길이 비어 있으면 얼마든지 갑니다.", ["가로 또는 세로만 갑니다. 대각선은 안 되고 뛰어넘지도 못합니다.", "빈 칸에 서거나 상대 기물 위에 서서 잡습니다. 아군 위에는 설 수 없습니다.", "양쪽 폰이 없는 열린 파일에서 가장 강합니다.", "a1의 룩을 a파일을 따라 a8까지 보내세요."], "a1의 룩을 누르고 a8을 누르세요.", "사이에 기물이 없어 a파일 전체를 갑니다."),
  knight: L("나이트", "나이트만 다른 기물을 뛰어넘습니다. 움직임은 항상 L자입니다.", ["한 방향으로 두 칸, 그다음 옆으로 한 칸. 또는 한 칸 뒤 두 칸.", "아군과 적군 위를 뜁니다. 도착칸이 비면 이동, 적이 있으면 잡습니다.", "둘 때마다 칸 색이 바뀝니다. 검은 칸에서 흰 칸으로, 그 반대도 같습니다.", "나이트를 b1에서 c3로 보내세요."], "b1의 나이트를 누르고 c3를 누르세요.", "위로 두 칸, 오른쪽으로 한 칸이 L입니다. 길이 빌 필요가 없습니다."),
  bishop: L("비숍", "비숍은 대각선으로만 가고, 대국 내내 같은 색 칸에 머뭅니다.", ["대각선은 얼마든지, 하지만 뛰어넘지는 못합니다.", "검은 칸에서 시작한 비숍은 흰 칸에 갈 수 없습니다. 그래서 두 비숍은 서로 다른 색을 봅니다.", "이 비숍은 검은 칸 c1에 있습니다. g5도 같은 대각선의 검은 칸입니다.", "g5로 보내세요."], "c1의 비숍을 누르고 g5를 누르세요.", "칸 색은 그대로입니다. 흰 칸으로는 절대 바뀌지 않습니다."),
  queen: L("퀸", "퀸은 룩과 비숍을 합친 움직임입니다. 가로, 세로, 대각선.", ["거리는 자유지만 뛰어넘지 못합니다.", "두 방향을 오갈 수 있어 가장 강합니다. 잃으면 국면도 잃기 쉽습니다.", "d1에서 룩처럼 세로로, 비숍처럼 대각선으로 갈 수 있습니다.", "대각선을 따라 h5로 보내세요."], "d1의 퀸을 누르고 h5를 누르세요.", "긴 대각선입니다. 세로로 d8에 갈 수도 있었습니다."),
  check: L("킹과 체크", "킹은 느리고 한 번에 한 칸만 갑니다. 위험한 칸에는 들어갈 수 없습니다.", ["가로, 세로, 대각선 어느 방향으로든 한 칸입니다.", "상대가 공격하는 칸에는 갈 수 없고, 상대 킹 옆에도 설 수 없습니다.", "체크는 킹이 공격받는 상태입니다. 당장 벗어나야 합니다. 킹을 옮기거나, 길을 막거나, 체크하는 기물을 잡습니다.", "검은 룩이 1랭크에서 흰 킹을 체크합니다. 체크에서 벗어나세요."], "1랭크에 남을 수 없습니다. 한 칸 위로.", "룩이 지배하는 랭크를 벗어났습니다. 남으면 반칙입니다."),
  mate: L("체크메이트", "체크메이트는 킹이 피할 수도, 막을 수도, 체크하는 기물을 잡을 수도 없는 체크입니다.", ["보통 체크와 달리 상대에게 합법적인 수가 하나도 없습니다.", "킹은 보드에서 제거되지 않습니다. 대국이 끝나고 메이트한 쪽이 이깁니다.", "이것은 스콜라 메이트입니다. 퀸은 h5, 비숍은 c4에서 f7을 봅니다.", "퀸으로 f7의 폰을 잡으세요."], "h5의 퀸을 누르고 f7을 누르세요.", "f7의 퀸은 c4 비숍의 보호를 받습니다. 검은 킹은 잡을 수도, 막을 수도, 달아날 칸도 없습니다."),
  draw: L("무승부와 스테일메이트", "킹이 갇혔다고 항상 승리는 아닙니다. 둘 차례에 합법적인 수가 없고 체크도 아니면 스테일메이트, 즉 무승부입니다.", ["흑 차례입니다. a8의 킹은 체크가 아니지만 a7, b7, b8은 모두 흰 퀸이 지배합니다. 흑은 수가 없습니다.", "이것이 스테일메이트입니다. 흑의 패배가 아닙니다. 구석으로 몰아넣고 체크를 빠뜨리면 이긴 판을 놓칩니다.", "같은 국면이 세 번, 잡기나 폰 전진 없는 50수, 메이트할 기물 부족, 합의 무승부도 무승부입니다.", "킹 대 킹, 킹과 나이트, 킹과 비숍은 메이트를 강제할 수 없습니다."], "이 국면은 이미 무승부입니다. 다음은 캐슬링입니다."),
  castle: L("캐슬링", "캐슬링은 한 수에 기물 둘을 움직이는 유일한 수입니다. 킹은 구석으로, 룩은 나옵니다.", ["킹이 룩 쪽으로 두 칸 갑니다. 룩은 킹을 넘어 바로 옆에 섭니다.", "백에게 오른쪽 킹사이드는 짧은 캐슬링, 왼쪽 퀸사이드는 긴 캐슬링입니다.", "그 킹과 룩이 움직이지 않았고, 사이가 비었고, 킹이 체크가 아니며, 공격받는 칸을 지나거나 멈추지 않을 때만 가능합니다.", "각 진영은 한 번만 합니다. 킹사이드: 킹을 e1에서 g1로."], "e1의 킹을 누르고 g1을 누르세요. h1의 룩은 스스로 f1로 뜁니다.", "킹은 g1, 룩은 f1. 이것은 한 수지 두 수가 아닙니다."),
  passant: L("앙파상", "상대 폰이 방금 두 칸 뛰어 내 폰 옆에 멈췄다면, 한 칸만 온 것처럼 잡을 수 있습니다.", ["검은 폰이 d7에서 d5로 뛰어 e5의 흰 폰과 나란히 있습니다.", "백은 대각선으로 d6에 잡을 수 있습니다. 도착은 d6이지만 d5의 검은 폰은 사라집니다.", "이 권리는 바로 다음 한 수뿐입니다. 다른 수를 두면 사라집니다.", "앙파상: e5의 폰을 d6으로."], "e5의 흰 폰을 누르고 d6을 누르세요.", "도착한 칸에 없어도 검은 폰은 잡힙니다. 잡힌 기물의 칸이 아닌 곳에 서는 유일한 잡기입니다."),
  promote: L("프로모션", "마지막 랭크에 간 폰은 더 이상 폰이 아닙니다. 퀸, 룩, 비숍, 나이트 중 하나로 바꿔야 합니다.", ["백은 8랭크, 흑은 1랭크입니다. 교체는 필수이며 같은 수 안에서 일어납니다.", "대개 퀸을 고릅니다. 가장 많은 방향으로 가기 때문입니다.", "나이트의 점프가 바로 체크가 되면 나이트가 더 강할 때도 있습니다.", "e7의 폰을 e8로 올리고 퀸으로 바꾸세요."], "e7의 폰을 누르고 e8을 누른 뒤 퀸을 고르세요.", "폰이 퀸이 되었습니다. 마지막 랭크의 폰은 대국을 바꿉니다."),
};

const es: Record<string, Copy> = {
  goal: L("El objetivo", "El ajedrez es un combate de dos ejércitos en 64 casillas. No hace falta capturar todas las piezas: basta con dejar al rey enemigo sin escape.", ["El tablero tiene columnas a–h y filas 1–8. Cada bando empieza con 8 peones, 2 torres, 2 caballos, 2 alfiles, 1 dama y 1 rey.", "Las blancas mueven primero y luego se alterna, una jugada cada vez.", "Se gana por jaque mate: el rey enemigo está atacado y no hay jugada legal para escapar.", "El rey nunca se captura. La partida se detiene en el mate.", "Hay tablas por ahogado, repetición, material insuficiente, la regla de 50 jugadas o acuerdo."], "Cuando lo hayas leído, pasa a la siguiente lección."),
  controls: L("Cómo mover", "En este tablero una jugada son dos toques: elige una pieza y luego una casilla.", ["Toca una pieza del bando que juega. Las casillas legales se iluminan.", "Un punto es una casilla vacía. Un aro es una pieza enemiga: tócala para capturarla.", "Toca otra pieza propia para cambiar la elección. Una casilla ilegal cancela.", "Arrastra para orbitar. Las flechas mueven la cámara. + acerca la pieza elegida, − aleja y el cuadrado encuadra todo el tablero.", "Prueba cualquier jugada legal de las blancas."], "Elige una pieza blanca y toca una casilla iluminada.", "Correcto. Una casilla iluminada es legal; una apagada no se puede alcanzar."),
  pawn: L("El peón", "El peón es lento y solo avanza, pero es la única pieza que captura en una dirección distinta de la que se mueve.", ["Avanza una casilla recta si está vacía. No puede retroceder.", "Desde su fila inicial puede avanzar dos si las dos de delante están vacías.", "Captura una casilla en diagonal hacia delante, nunca de frente.", "En la última fila debe coronarse.", "El peón blanco está en e4. Captura el peón negro de d5."], "Toca el peón blanco y luego d5.", "El peón captura en diagonal. Ir recto a e5 no tomaría la pieza de la diagonal."),
  rook: L("La torre", "La torre se mueve por filas y columnas, todo lo lejos que quiera si el camino está libre.", ["Va en horizontal o vertical, nunca en diagonal, y no salta.", "Puede parar en una casilla vacía o sobre una pieza enemiga para capturarla. No puede posarse sobre una pieza propia.", "Es más fuerte en una columna abierta, sin peones de ningún bando.", "Lleva la torre de a1 hasta el final de la columna a, a a8."], "Toca la torre de a1 y luego a8.", "La torre recorre toda la columna a porque no hay nadie en medio."),
  knight: L("El caballo", "El caballo es la única pieza que salta. Su movimiento es siempre una L.", ["Dos casillas en una dirección y luego una de lado. O una y luego dos.", "Salta sobre piezas propias y enemigas. Si el destino está vacío, mueve; si hay un enemigo, captura.", "Cada jugada cambia el color de su casilla: de una oscura cae en una clara, y al revés.", "Lleva el caballo de b1 a c3."], "Toca el caballo de b1 y luego c3.", "Dos hacia arriba y una a la derecha: esa es la L. No necesita camino libre."),
  bishop: L("El alfil", "El alfil solo se mueve en diagonal y permanece en un color de casilla durante toda la partida.", ["Puede ir cualquier distancia en diagonal, pero no salta.", "Un alfil que empieza en casilla oscura nunca llega a una clara. Por eso los dos alfiles vigilan colores distintos.", "Este alfil está en c1, una casilla oscura. g5 también es oscura, en la misma diagonal.", "Llévalo a g5."], "Toca el alfil de c1 y luego g5.", "El alfil conservó su color. Nunca pasa a una casilla clara."),
  queen: L("La dama", "La dama se mueve como torre y alfil a la vez: en horizontal, vertical o diagonal.", ["Cualquier distancia, pero no salta.", "Es la pieza más fuerte porque cambia entre ambas direcciones. Perderla suele perder la posición.", "Desde d1 puede ir como torre por la columna o como alfil por la diagonal.", "Llévla por la diagonal hasta h5."], "Toca la dama de d1 y luego h5.", "Una diagonal larga. También podría haber ido recto hasta d8."),
  check: L("El rey y el jaque", "El rey se mueve despacio, solo una casilla, y nunca puede entrar en peligro.", ["Se mueve una casilla en cualquier dirección: horizontal, vertical o diagonal.", "No puede ir a una casilla atacada por el enemigo ni ponerse junto al rey enemigo.", "Jaque significa que el rey está atacado. Hay que salir enseguida: mover el rey, bloquear la línea o capturar la pieza que da jaque.", "La torre negra da jaque al rey blanco por la fila 1. Saca al rey del jaque."], "El rey no puede quedarse en la fila 1. Sube una casilla.", "El rey salió de la fila que controla la torre. Quedarse sería ilegal."),
  mate: L("Jaque mate", "El jaque mate es un jaque del que el rey no puede salir, que no se puede bloquear y cuya pieza no se puede capturar.", ["A diferencia de un jaque normal, el rival no tiene ninguna jugada legal.", "El rey no se retira del tablero. La partida termina y gana quien da mate.", "Este es el mate del pastor: la dama está en h5 y el alfil de c4 mira f7.", "Captura el peón de f7 con la dama."], "Toca la dama de h5 y luego f7.", "La dama de f7 está defendida por el alfil de c4. El rey negro no puede tomarla, no puede bloquear y no tiene casilla de escape."),
  draw: L("Tablas y ahogado", "No todo rey atrapado es una victoria. Si quien juega no tiene jugada legal y no está en jaque, hay tablas: es el ahogado.", ["Juegan las negras. El rey de a8 no está en jaque, pero a7, b7 y b8 las controla la dama blanca. Las negras no tienen jugada.", "Eso es ahogado: tablas, no derrota de las negras. Arrinconar al rey sin dar jaque puede tirar una partida ganada.", "También hay tablas si la misma posición se repite tres veces, tras 50 jugadas sin captura ni avance de peón, si no hay material para mate o si se acepta un ofrecimiento.", "Rey contra rey, rey y caballo, o rey y alfil no pueden forzar el mate."], "Esta posición ya es tablas. Sigue para aprender el enroque."),
  castle: L("Enroque", "El enroque es la única jugada que mueve dos piezas a la vez: el rey se esconde en la esquina y una torre sale.", ["El rey avanza dos casillas hacia una torre. La torre salta sobre el rey y se coloca a su lado.", "Para las blancas, el flanco de rey a la derecha es el enroque corto. El flanco de dama a la izquierda es el largo.", "Solo se puede si ese rey y esa torre no se han movido, las casillas intermedias están vacías, el rey no está en jaque y no cruza ni se detiene en una casilla atacada.", "Cada bando enroca solo una vez. Enroca en corto: lleva el rey de e1 a g1."], "Toca el rey de e1 y luego g1. La torre de h1 salta sola a f1.", "El rey va a g1 y la torre a f1. Es una jugada, no dos."),
  passant: L("Captura al paso", "Si un peón enemigo acaba de saltar dos casillas y se detiene junto al tuyo, puedes capturarlo como si hubiera avanzado solo una.", ["El peón negro acaba de saltar de d7 a d5, junto al peón blanco de e5.", "Las blancas pueden capturar en diagonal a d6. El peón negro de d5 desaparece aunque aterrices en d6.", "El derecho dura solo la jugada inmediata. Cualquier otra jugada lo pierde.", "Captura al paso: el peón de e5 va a d6."], "Toca el peón blanco de e5 y luego d6.", "El peón negro es capturado aunque no está en la casilla a la que vas. Es la única captura que no cae sobre la pieza tomada."),
  promote: L("Coronación", "Un peón que llega a la última fila deja de ser peón. Debes convertirlo en dama, torre, alfil o caballo.", ["Las blancas coronan en la fila 8. Las negras, en la 1. El cambio es obligatorio y ocurre en la misma jugada.", "Casi siempre conviene la dama, porque cubre más direcciones.", "A veces un caballo es mejor si su salto da jaque al rey enemigo al instante.", "Avanza el peón de e7 a e8 y corónalo en dama."], "Toca el peón de e7, toca e8 y elige Dama.", "El peón se convirtió en dama. Un peón en la última fila suele cambiar la partida."),
};

const packs: Partial<Record<Lang, Record<string, Copy>>> = { en, zh, ja, ko, es };

const fr: Record<string, Copy> = {
  goal: L("Le but", "Les échecs opposent deux armées sur 64 cases. Inutile de tout prendre : il suffit que le roi adverse n'ait plus d'échappatoire.", ["L'échiquier a les colonnes a–h et les rangées 1–8. Chaque camp commence avec 8 pions, 2 tours, 2 cavaliers, 2 fous, 1 dame et 1 roi.", "Les Blancs jouent en premier, puis on alterne, un coup chacun.", "On gagne par échec et mat : le roi adverse est attaqué et aucun coup légal ne le sauve.", "Le roi n'est jamais pris. La partie s'arrête au mat.", "Partie nulle en cas de pat, répétition, matériel insuffisant, règle des 50 coups ou accord."], "Quand tu as lu, passe à la leçon suivante."),
  controls: L("Comment jouer", "Sur cet échiquier, un coup se fait en deux touches : choisir une pièce, puis une case.", ["Touche une pièce du camp qui doit jouer. Les cases légales s'éclairent.", "Un point est une case vide. Un anneau est une pièce adverse : touche-la pour la prendre.", "Touche une autre pièce alliée pour changer. Une case illégale annule.", "Glisse pour tourner. Les flèches déplacent la caméra. + zoome sur la pièce choisie, − éloigne, le carré cadre tout l'échiquier.", "Essaie n'importe quel coup légal des Blancs."], "Choisis une pièce blanche, puis touche une case éclairée.", "Juste. Une case éclairée est légale ; une case éteinte est inaccessible."),
  pawn: L("Le pion", "Le pion est lent et n'avance que vers l'avant, mais c'est la seule pièce qui prend dans une autre direction que celle où elle avance.", ["Il avance d'une case tout droit si elle est vide. Il ne recule pas.", "Depuis sa rangée de départ, il peut avancer de deux cases si les deux devant sont vides.", "Il prend une case en diagonale vers l'avant, jamais de face.", "Sur la dernière rangée, il doit être promu.", "Le pion blanc est en e4. Prends le pion noir en d5."], "Touche le pion blanc, puis d5.", "Le pion prend en diagonale. Aller tout droit en e5 ne prendrait pas la pièce sur la diagonale."),
  rook: L("La tour", "La tour se déplace sur les rangées et les colonnes, aussi loin qu'elle veut si le chemin est libre.", ["Horizontal ou vertical, jamais en diagonale, et elle ne saute pas.", "Elle peut s'arrêter sur une case vide ou sur une pièce adverse pour la prendre. Pas sur une pièce alliée.", "Elle est plus forte sur une colonne ouverte, sans pion d'aucun camp.", "Mène la tour de a1 jusqu'au bout de la colonne a, en a8."], "Touche la tour en a1, puis a8.", "La tour parcourt toute la colonne a car rien ne se trouve entre les deux."),
  knight: L("Le cavalier", "Le cavalier est la seule pièce qui saute. Son mouvement est toujours un L.", ["Deux cases dans un sens, puis une sur le côté. Ou une, puis deux.", "Il saute amis et ennemis. Une case vide est un déplacement ; un ennemi, une prise.", "Chaque coup change la couleur de sa case : d'une case noire il arrive sur une blanche, et l'inverse.", "Mène le cavalier de b1 à c3."], "Touche le cavalier en b1, puis c3.", "Deux cases vers le haut et une à droite : c'est le L. Il n'a pas besoin d'un chemin libre."),
  bishop: L("Le fou", "Le fou ne va qu'en diagonale et reste sur une seule couleur de case pendant toute la partie.", ["Il peut aller aussi loin qu'il veut en diagonale, mais ne saute pas.", "Un fou parti d'une case noire n'atteint jamais une case blanche. Les deux fous d'un camp surveillent donc deux couleurs.", "Ce fou est en c1, une case noire. g5 est aussi noire, sur la même diagonale.", "Mène-le en g5."], "Touche le fou en c1, puis g5.", "Le fou a gardé sa couleur. Il ne passe jamais sur une case blanche."),
  queen: L("La dame", "La dame se déplace comme une tour et un fou : horizontal, vertical ou diagonal.", ["Aussi loin qu'elle veut, mais sans sauter.", "C'est la pièce la plus forte car elle change de direction. La perdre fait souvent perdre la position.", "Depuis d1, elle peut aller comme une tour sur la colonne ou comme un fou en diagonale.", "Mène-la en diagonale jusqu'à h5."], "Touche la dame en d1, puis h5.", "Une longue diagonale. Elle aurait aussi pu aller tout droit en d8."),
  check: L("Le roi et l'échec", "Le roi avance lentement, d'une seule case, et ne peut jamais entrer dans le danger.", ["Il va d'une case dans toutes les directions : horizontal, vertical ou diagonal.", "Il ne peut pas aller sur une case attaquée, ni se placer à côté du roi adverse.", "L'échec signifie que le roi est attaqué. Il faut sortir tout de suite : bouger le roi, bloquer la ligne ou prendre la pièce qui fait échec.", "La tour noire fait échec au roi blanc sur la rangée 1. Sors le roi de l'échec."], "Le roi ne peut pas rester sur la rangée 1. Monte d'une case.", "Le roi a quitté la rangée contrôlée par la tour. Y rester serait illégal."),
  mate: L("Échec et mat", "Le mat est un échec dont le roi ne peut ni sortir, ni être protégé par un blocage, ni capturer la pièce qui fait échec.", ["Contrairement à un échec simple, l'adversaire n'a plus aucun coup légal.", "Le roi n'est pas retiré de l'échiquier. La partie s'arrête et le camp qui mate gagne.", "C'est le mat du berger : la dame est en h5 et le fou en c4 vise f7.", "Prends le pion en f7 avec la dame."], "Touche la dame en h5, puis f7.", "La dame en f7 est défendue par le fou en c4. Le roi noir ne peut pas la prendre, ni bloquer, ni fuir."),
  draw: L("Nulles et pat", "Un roi coincé n'est pas toujours une victoire. Si le camp qui doit jouer n'a aucun coup légal et n'est pas en échec, c'est nulle : un pat.", ["Trait aux Noirs. Le roi en a8 n'est pas en échec, mais a7, b7 et b8 sont contrôlées par la dame blanche. Les Noirs n'ont aucun coup.", "C'est un pat : nulle, pas une défaite des Noirs. Acculer le roi sans donner échec peut gâcher une partie gagnée.", "Il y a aussi nulle si la même position revient trois fois, après 50 coups sans prise ni poussée de pion, si le matériel ne permet pas le mat, ou si une nulle est acceptée.", "Roi contre roi, roi et cavalier, ou roi et fou ne peuvent pas forcer le mat."], "Cette position est déjà nulle. Continue pour apprendre le roque."),
  castle: L("Le roque", "Le roque est le seul coup qui déplace deux pièces à la fois : le roi se cache dans le coin et une tour sort.", ["Le roi avance de deux cases vers une tour. La tour saute par-dessus le roi et se place à côté de lui.", "Pour les Blancs, l'aile roi à droite est le petit roque. L'aile dame à gauche est le grand roque.", "On ne peut roquer que si ce roi et cette tour n'ont pas bougé, si les cases entre eux sont vides, si le roi n'est pas en échec et s'il ne traverse ni ne s'arrête sur une case attaquée.", "Chaque camp ne roque qu'une fois. Petit roque : mène le roi de e1 à g1."], "Touche le roi en e1, puis g1. La tour en h1 saute seule en f1.", "Le roi va en g1 et la tour en f1. C'est un seul coup, pas deux."),
  passant: L("La prise en passant", "Si un pion adverse vient de sauter deux cases et s'arrête à côté du tien, tu peux le prendre comme s'il n'avait avancé que d'une case.", ["Le pion noir vient de sauter de d7 à d5, à côté du pion blanc en e5.", "Les Blancs peuvent prendre en diagonale vers d6. Le pion noir en d5 disparaît, même si tu arrives en d6.", "Ce droit ne dure que le coup suivant. Tout autre coup le fait perdre.", "Prends en passant : le pion en e5 va en d6."], "Touche le pion blanc en e5, puis d6.", "Le pion noir est pris alors qu'il n'est pas sur la case d'arrivée. C'est la seule prise qui n'atterrit pas sur la pièce prise."),
  promote: L("La promotion", "Un pion qui atteint la dernière rangée n'est plus un pion. Tu dois le changer en dame, tour, fou ou cavalier.", ["Les Blancs promeuvent sur la rangée 8, les Noirs sur la 1. Le changement est obligatoire et se fait dans le même coup.", "Le plus souvent, choisis la dame : elle couvre le plus de directions.", "Parfois un cavalier est plus fort si son saut fait échec tout de suite.", "Pousse le pion de e7 à e8 et promeus-le en dame."], "Touche le pion en e7, touche e8, puis choisis Dame.", "Le pion est devenu une dame. Un pion sur la dernière rangée change souvent la partie."),
};

const de: Record<string, Copy> = {
  goal: L("Das Ziel", "Schach ist ein Kampf zweier Heere auf 64 Feldern. Du musst nicht alle Figuren schlagen — nur den gegnerischen König ohne Flucht lassen.", ["Das Brett hat die Linien a–h und die Reihen 1–8. Jede Seite beginnt mit 8 Bauern, 2 Türmen, 2 Springern, 2 Läufern, 1 Dame und 1 König.", "Weiß zieht zuerst, danach abwechselnd je ein Zug.", "Sieg durch Schachmatt: Der gegnerische König wird angegriffen und kein legaler Zug rettet ihn.", "Der König wird nie geschlagen. Die Partie endet beim Matt.", "Remis durch Patt, Wiederholung, zu wenig Material, die 50-Züge-Regel oder Einigung."], "Wenn du das gelesen hast, geh zur nächsten Lektion."),
  controls: L("So zieht man", "Auf diesem Brett ist ein Zug zwei Tippbewegungen: Figur wählen, dann Feld wählen.", ["Tippe eine Figur der Seite am Zug. Legale Felder leuchten.", "Ein Punkt ist ein leeres Feld. Ein Ring ist eine gegnerische Figur — tippe sie, um zu schlagen.", "Eine andere eigene Figur wechselt die Wahl. Ein illegales Feld bricht ab.", "Ziehen dreht die Sicht. Die Pfeile schwenken die Kamera. + zoomt zur gewählten Figur, − heraus, das Quadrat zeigt das ganze Brett.", "Probiere irgendeinen legalen Zug für Weiß."], "Wähle eine weiße Figur und tippe ein leuchtendes Feld.", "Richtig. Ein leuchtendes Feld ist legal. Ein dunkles ist unerreichbar."),
  pawn: L("Der Bauer", "Der Bauer ist langsam und zieht nur vorwärts, schlägt aber als einzige Figur in eine andere Richtung, als er zieht.", ["Er zieht ein Feld geradeaus, wenn es leer ist. Rückwärts geht nicht.", "Von der Grundreihe darf er zwei Felder ziehen, wenn beide frei sind.", "Er schlägt ein Feld schräg nach vorn, nie geradeaus.", "Auf der letzten Reihe muss er sich umwandeln.", "Der weiße Bauer steht auf e4. Schlage den schwarzen Bauern auf d5."], "Tippe den weißen Bauern, dann d5.", "Bauern schlagen schräg. Gerade nach e5 würde die Figur auf der Diagonale nicht nehmen."),
  rook: L("Der Turm", "Der Turm zieht auf Reihen und Linien, so weit er will, wenn der Weg frei ist.", ["Waagerecht oder senkrecht, nie diagonal, und er springt nicht.", "Er darf auf einem leeren Feld stehen oder auf einer gegnerischen Figur, um sie zu schlagen. Nicht auf einer eigenen.", "Am stärksten ist er auf einer offenen Linie, ohne Bauern beider Seiten.", "Zieh den Turm von a1 die ganze a-Linie hinauf nach a8."], "Tippe den Turm auf a1, dann a8.", "Der Turm läuft die ganze a-Linie, weil nichts dazwischen steht."),
  knight: L("Der Springer", "Der Springer ist die einzige Figur, die springt. Sein Zug ist immer ein L.", ["Zwei Felder in eine Richtung, dann eines seitwärts. Oder eines, dann zwei.", "Er springt über Freunde und Gegner. Ein leeres Zielfeld ist ein Zug, ein Gegner dort ein Schlag.", "Jeder Zug wechselt die Feldfarbe: von einem dunklen Feld auf ein helles und umgekehrt.", "Zieh den Springer von b1 nach c3."], "Tippe den Springer auf b1, dann c3.", "Zwei nach oben und eines nach rechts — das ist das L. Er braucht keinen freien Weg."),
  bishop: L("Der Läufer", "Der Läufer zieht nur diagonal und bleibt die ganze Partie auf einer Feldfarbe.", ["Beliebig weit diagonal, aber er springt nicht.", "Ein Läufer, der auf einem dunklen Feld beginnt, erreicht nie ein helles. Die beiden Läufer einer Seite bewachen daher verschiedene Farben.", "Dieser Läufer steht auf c1, einem dunklen Feld. g5 ist ebenfalls dunkel, auf derselben Diagonale.", "Zieh ihn nach g5."], "Tippe den Läufer auf c1, dann g5.", "Der Läufer behielt seine Feldfarbe. Er wechselt nie auf ein helles Feld."),
  queen: L("Die Dame", "Die Dame zieht wie Turm und Läufer zusammen: seitwärts, gerade oder diagonal.", ["Beliebig weit, aber sie springt nicht.", "Sie ist die stärkste Figur, weil sie beide Richtungen wechseln kann. Sie zu verlieren verliert oft die Stellung.", "Von d1 kann sie wie ein Turm die Linie entlang oder wie ein Läufer diagonal ziehen.", "Zieh sie diagonal nach h5."], "Tippe die Dame auf d1, dann h5.", "Eine lange Diagonale. Sie hätte auch gerade nach d8 gehen können."),
  check: L("König und Schach", "Der König zieht langsam, nur ein Feld, und darf nie in Gefahr treten.", ["Er zieht ein Feld in jede Richtung: seitwärts, gerade oder diagonal.", "Er darf nicht auf ein angegriffenes Feld und nicht neben den gegnerischen König.", "Schach heißt: Der König wird angegriffen. Du musst sofort heraus: König ziehen, die Linie verstellen oder die schachbietende Figur schlagen.", "Der schwarze Turm gibt dem weißen König auf der 1. Reihe Schach. Zieh den König aus dem Schach."], "Der König darf nicht auf der 1. Reihe bleiben. Geh ein Feld nach oben.", "Der König hat die Reihe verlassen, die der Turm beherrscht. Bleiben wäre illegal."),
  mate: L("Schachmatt", "Matt ist ein Schach, das der König nicht verlassen, nicht verstellen und nicht durch Schlagen der bietenden Figur beantworten kann.", ["Anders als bei einem gewöhnlichen Schach hat die Gegenseite keinen legalen Zug mehr.", "Der König wird nicht vom Brett genommen. Die Partie endet, die mattsetzende Seite gewinnt.", "Das ist das Hirtenmatt: Die Dame steht auf h5, der Läufer auf c4 sieht auf f7.", "Schlage den Bauern auf f7 mit der Dame."], "Tippe die Dame auf h5, dann f7.", "Die Dame auf f7 wird vom Läufer auf c4 gedeckt. Der schwarze König kann sie nicht schlagen, nicht verstellen und hat kein Fluchtfeld."),
  draw: L("Remis und Patt", "Nicht jeder gefangene König ist ein Sieg. Hat die Seite am Zug keinen legalen Zug und steht nicht im Schach, ist die Partie remis — das ist Patt.", ["Schwarz ist am Zug. Der König auf a8 steht nicht im Schach, aber a7, b7 und b8 beherrscht die weiße Dame. Schwarz hat keinen Zug.", "Das ist Patt: Remis, keine Niederlage für Schwarz. Den König in die Ecke zu treiben, ohne Schach zu geben, kann einen Sieg verschenken.", "Remis gibt es auch bei dreifacher Stellungswiederholung, nach 50 Zügen ohne Schlag oder Bauernzug, bei zu wenig Material oder wenn ein Remisangebot angenommen wird.", "König gegen König, König und Springer oder König und Läufer können kein Matt erzwingen."], "Diese Stellung ist schon remis. Weiter geht es mit der Rochade."),
  castle: L("Rochade", "Die Rochade ist der einzige Zug, der zwei Figuren zugleich bewegt: Der König versteckt sich in der Ecke, ein Turm kommt heraus.", ["Der König zieht zwei Felder auf einen Turm zu. Der Turm springt über den König und landet neben ihm.", "Für Weiß ist die Königseite rechts die kurze Rochade. Die Damenseite links ist die lange.", "Nur möglich, wenn König und dieser Turm noch nicht gezogen haben, die Felder dazwischen leer sind, der König nicht im Schach steht und weder ein angegriffenes Feld überquert noch darauf landet.", "Jede Seite rochiert nur einmal. Rochiere kurz: König von e1 nach g1."], "Tippe den König auf e1, dann g1. Der Turm auf h1 springt von selbst nach f1.", "Der König geht nach g1, der Turm nach f1. Das ist ein Zug, nicht zwei."),
  passant: L("En passant", "Wenn ein gegnerischer Bauer gerade zwei Felder gesprungen ist und neben deinem Bauern steht, darfst du ihn schlagen, als wäre er nur eines gezogen.", ["Der schwarze Bauer sprang gerade von d7 nach d5, neben den weißen Bauern auf e5.", "Weiß darf schräg nach d6 schlagen. Der schwarze Bauer auf d5 verschwindet, obwohl du auf d6 landest.", "Das Recht gilt nur für den unmittelbar nächsten Zug. Jeder andere Zug verliert es.", "Schlage en passant: Der Bauer auf e5 geht nach d6."], "Tippe den weißen Bauern auf e5, dann d6.", "Der schwarze Bauer wird geschlagen, obwohl er nicht auf dem Feld steht, auf dem du landest. Das ist der einzige Schlag, der nicht auf der geschlagenen Figur endet."),
  promote: L("Umwandlung", "Ein Bauer auf der letzten Reihe ist kein Bauer mehr. Du musst ihn in Dame, Turm, Läufer oder Springer verwandeln.", ["Weiß wandelt auf der 8. Reihe um, Schwarz auf der 1. Die Änderung ist Pflicht und geschieht im selben Zug.", "Meist wählt man die Dame, weil sie die meisten Richtungen abdeckt.", "Manchmal ist ein Springer stärker, wenn sein Sprung sofort Schach gibt.", "Zieh den Bauern von e7 nach e8 und wandle ihn in eine Dame um."], "Tippe den Bauern auf e7, tippe e8 und wähle Dame.", "Der Bauer wurde zur Dame. Ein Bauer auf der letzten Reihe verändert oft die ganze Partie."),
};

const pt: Record<string, Copy> = {
  goal: L("O objetivo", "O xadrez é uma luta de dois exércitos em 64 casas. Não é preciso capturar todas as peças — basta deixar o rei inimigo sem fuga.", ["O tabuleiro tem colunas a–h e filas 1–8. Cada lado começa com 8 peões, 2 torres, 2 cavalos, 2 bispos, 1 dama e 1 rei.", "As brancas jogam primeiro. Depois alterna-se, um lance de cada vez.", "Ganha-se por xeque-mate: o rei inimigo está atacado e nenhum lance legal escapa.", "O rei nunca é capturado. O jogo para no mate.", "Há empate por afogamento, repetição, material insuficiente, regra dos 50 lances ou acordo."], "Quando tiver lido, passe à lição seguinte."),
  controls: L("Como jogar", "Neste tabuleiro um lance são dois toques: escolher uma peça e depois uma casa.", ["Toque numa peça do lado a jogar. As casas legais acendem-se.", "Um ponto é uma casa vazia. Um anel é uma peça inimiga — toque para capturar.", "Toque noutra peça sua para mudar a escolha. Uma casa ilegal cancela.", "Arraste para orbitar. As setas movem a câmara. + aproxima a peça escolhida, − afasta e o quadrado enquadra o tabuleiro.", "Experimente qualquer lance legal das brancas."], "Escolha uma peça branca e toque numa casa acesa.", "Certo. Uma casa acesa é legal. Uma apagada não pode ser alcançada."),
  pawn: L("O peão", "O peão é lento e só avança, mas é a única peça que captura numa direção diferente daquela em que se move.", ["Avança uma casa em frente se estiver vazia. Não recua.", "Na fila inicial pode avançar duas casas se as duas à frente estiverem vazias.", "Captura uma casa na diagonal à frente, nunca em frente.", "Na última fila tem de ser promovido.", "O peão branco está em e4. Capture o peão preto em d5."], "Toque no peão branco e depois em d5.", "O peão captura na diagonal. Ir em frente para e5 não comeria a peça na diagonal."),
  rook: L("A torre", "A torre move-se por filas e colunas, tão longe quanto quiser se o caminho estiver livre.", ["Na horizontal ou na vertical, nunca na diagonal, e não salta.", "Pode parar numa casa vazia ou sobre uma peça inimiga para a capturar. Não pousa sobre uma peça sua.", "É mais forte numa coluna aberta, sem peões de nenhum lado.", "Leve a torre de a1 até ao fim da coluna a, a a8."], "Toque na torre em a1 e depois em a8.", "A torre percorre a coluna a inteira porque não há ninguém no meio."),
  knight: L("O cavalo", "O cavalo é a única peça que salta. O movimento é sempre um L.", ["Duas casas numa direção e depois uma para o lado. Ou uma e depois duas.", "Salta amigos e inimigos. Destino vazio é movimento; inimigo ali é captura.", "Cada lance muda a cor da casa: de uma escura cai numa clara, e o inverso.", "Leve o cavalo de b1 a c3."], "Toque no cavalo em b1 e depois em c3.", "Duas para cima e uma para a direita — isso é o L. Não precisa de caminho livre."),
  bishop: L("O bispo", "O bispo só anda na diagonal e fica numa cor de casa durante todo o jogo.", ["Pode ir qualquer distância na diagonal, mas não salta.", "Um bispo que começa numa casa escura nunca chega a uma clara. Os dois bispos de um lado vigiam cores diferentes.", "Este bispo está em c1, uma casa escura. g5 também é escura, na mesma diagonal.", "Leve-o a g5."], "Toque no bispo em c1 e depois em g5.", "O bispo manteve a cor. Nunca passa para uma casa clara."),
  queen: L("A dama", "A dama move-se como torre e bispo juntos: na horizontal, vertical ou diagonal.", ["Qualquer distância, mas não salta.", "É a peça mais forte porque muda entre as duas direções. Perdê-la costuma perder a posição.", "De d1 pode ir como torre pela coluna ou como bispo na diagonal.", "Leve-a pela diagonal até h5."], "Toque na dama em d1 e depois em h5.", "Uma diagonal longa. Também poderia ter ido em frente até d8."),
  check: L("O rei e o xeque", "O rei move-se devagar, só uma casa, e nunca pode entrar em perigo.", ["Move-se uma casa em qualquer direção: horizontal, vertical ou diagonal.", "Não pode ir para uma casa atacada nem ficar ao lado do rei inimigo.", "Xeque significa que o rei está atacado. É preciso sair já: mover o rei, bloquear a linha ou capturar a peça que dá xeque.", "A torre preta dá xeque ao rei branco na fila 1. Tire o rei do xeque."], "O rei não pode ficar na fila 1. Suba uma casa.", "O rei saiu da fila que a torre controla. Ficar seria ilegal."),
  mate: L("Xeque-mate", "O mate é um xeque de que o rei não sai, que não se bloqueia e cuja peça não se pode capturar.", ["Ao contrário de um xeque normal, o adversário não tem nenhum lance legal.", "O rei não sai do tabuleiro. O jogo acaba e quem dá mate ganha.", "Este é o mate do pastor: a dama está em h5 e o bispo em c4 olha para f7.", "Capture o peão em f7 com a dama."], "Toque na dama em h5 e depois em f7.", "A dama em f7 está defendida pelo bispo em c4. O rei preto não a captura, não bloqueia e não tem casa de fuga."),
  draw: L("Empates e afogamento", "Nem todo rei encurralado é uma vitória. Se quem joga não tem lance legal e não está em xeque, é empate — um afogamento.", ["Jogam as pretas. O rei em a8 não está em xeque, mas a7, b7 e b8 são controladas pela dama branca. As pretas não têm lance.", "Isso é afogamento: empate, não derrota das pretas. Empurrar o rei para o canto sem dar xeque pode deitar fora uma vitória.", "Também há empate se a mesma posição se repetir três vezes, após 50 lances sem captura nem avanço de peão, se não houver material para mate ou se um empate for aceite.", "Rei contra rei, rei e cavalo, ou rei e bispo não forçam mate."], "Esta posição já é empate. Siga para aprender o roque."),
  castle: L("Roque", "O roque é o único lance que move duas peças ao mesmo tempo: o rei esconde-se no canto e uma torre sai.", ["O rei anda duas casas em direção a uma torre. A torre salta o rei e fica na casa ao lado.", "Para as brancas, o flanco de rei à direita é o roque curto. O flanco de dama à esquerda é o longo.", "Só é possível se esse rei e essa torre não se moveram, as casas entre eles estão vazias, o rei não está em xeque e não atravessa nem para numa casa atacada.", "Cada lado faz roque só uma vez. Roque curto: leve o rei de e1 a g1."], "Toque no rei em e1 e depois em g1. A torre em h1 salta sozinha para f1.", "O rei vai a g1 e a torre a f1. É um lance, não dois."),
  passant: L("En passant", "Se um peão inimigo acabou de saltar duas casas e parou ao lado do seu, pode capturá-lo como se tivesse andado só uma.", ["O peão preto saltou de d7 para d5, ao lado do peão branco em e5.", "As brancas podem capturar na diagonal para d6. O peão preto em d5 desaparece, embora aterre em d6.", "O direito dura só o lance imediato. Qualquer outro lance perde-o.", "Capture en passant: o peão em e5 vai a d6."], "Toque no peão branco em e5 e depois em d6.", "O peão preto é capturado embora não esteja na casa para onde vai. É a única captura que não cai sobre a peça tomada."),
  promote: L("Promoção", "Um peão que chega à última fila deixa de ser peão. Tem de o transformar em dama, torre, bispo ou cavalo.", ["As brancas promovem na fila 8. As pretas na 1. A mudança é obrigatória e acontece no mesmo lance.", "Quase sempre escolha a dama, porque cobre mais direções.", "Às vezes um cavalo é mais forte se o salto der xeque de imediato.", "Empurre o peão de e7 para e8 e promova-o a dama."], "Toque no peão em e7, toque em e8 e escolha Dama.", "O peão tornou-se dama. Um peão na última fila costuma mudar o jogo."),
};

const ru: Record<string, Copy> = {
  goal: L("Цель", "Шахматы — бой двух армий на 64 клетках. Не нужно брать все фигуры: достаточно оставить чужому королю без выхода.", ["На доске вертикали a–h и горизонтали 1–8. У каждой стороны вначале 8 пешек, 2 ладьи, 2 коня, 2 слона, 1 ферзь и 1 король.", "Белые ходят первыми, затем стороны чередуются.", "Победа — мат: король под ударом, и ни один законный ход не спасает.", "Короля не снимают с доски. Партия останавливается при мате.", "Ничья бывает при пате, троекратном повторении, недостатке материала, правиле 50 ходов или соглашении."], "Прочитав, переходите к следующему уроку."),
  controls: L("Как ходить", "На этой доске ход — это два нажатия: выбрать фигуру, затем клетку.", ["Нажмите фигуру стороны, чей ход. Доступные клетки загораются.", "Точка — пустая клетка. Кольцо — чужая фигура: нажмите, чтобы взять.", "Другая своя фигура меняет выбор. Недоступная клетка отменяет.", "Тяните, чтобы вращать вид. Стрелки двигают камеру. + приближает выбранную фигуру, − отдаляет, квадрат показывает всю доску.", "Сделайте любой законный ход белыми."], "Выберите белую фигуру и нажмите светящуюся клетку.", "Верно. Светящаяся клетка доступна, тёмная — нет."),
  pawn: L("Пешка", "Пешка медленная и ходит только вперёд, но это единственная фигура, которая бьёт не туда, куда ходит.", ["На пустое поле впереди — на одну клетку. Назад нельзя.", "С начальной горизонтали можно на две, если обе клетки свободны.", "Бьёт на одну клетку по диагонали вперёд, никогда прямо.", "На последней горизонтали обязана превратиться.", "Белая пешка на e4. Возьмите чёрную пешку на d5."], "Нажмите белую пешку, затем d5.", "Пешка бьёт по диагонали. Прямой ход на e5 не взял бы фигуру сбоку."),
  rook: L("Ладья", "Ладья ходит по горизонталям и вертикалям как угодно далеко, если путь свободен.", ["Только прямо, не по диагонали и не прыжком.", "Может встать на пустую клетку или на чужую фигуру, чтобы её взять. На свою — нельзя.", "Сильнее всего на открытой вертикали, где нет пешек обеих сторон.", "Проведите ладью с a1 до конца вертикали a, на a8."], "Нажмите ладью на a1, затем a8.", "Ладья проходит всю вертикаль a, потому что между ними никого нет."),
  knight: L("Конь", "Конь — единственная фигура, которая перепрыгивает. Его ход всегда буква Г.", ["Две клетки в одну сторону и одна вбок. Или одна, затем две.", "Прыгает через своих и чужих. Пустая клетка — ход, чужая фигура — взятие.", "Каждый ход меняет цвет клетки: с чёрной на белую и наоборот.", "Переведите коня с b1 на c3."], "Нажмите коня на b1, затем c3.", "Две вверх и одна вправо — это Г. Коню не нужен свободный путь."),
  bishop: L("Слон", "Слон ходит только по диагонали и всю партию остаётся на клетках одного цвета.", ["По диагонали на любое расстояние, но не прыжком.", "Слон с чёрной клетки никогда не попадёт на белую. Поэтому два слона стороны смотрят разные цвета.", "Этот слон на c1, чёрной клетке. g5 тоже чёрная, на той же диагонали.", "Переведите его на g5."], "Нажмите слона на c1, затем g5.", "Слон сохранил цвет. На белую клетку он не переходит."),
  queen: L("Ферзь", "Ферзь ходит как ладья и слон вместе: по горизонтали, вертикали или диагонали.", ["На любое расстояние, но не прыжком.", "Это сильнейшая фигура, потому что меняет оба направления. Потеря ферзя обычно теряет позицию.", "С d1 ферзь может пойти как ладья по вертикали или как слон по диагонали.", "Проведите его по диагонали на h5."], "Нажмите ферзя на d1, затем h5.", "Длинная диагональ. Он мог бы пойти и прямо на d8."),
  check: L("Король и шах", "Король ходит медленно, только на одну клетку, и не может шагнуть в опасность.", ["Одна клетка в любую сторону: прямо или по диагонали.", "Нельзя вставать на битую клетку и рядом с чужим королём.", "Шах значит, что король под ударом. Нужно сразу уйти: увести короля, закрыться или взять шахующую фигуру.", "Чёрная ладья даёт шах белому королю по первой горизонтали. Уйдите из шаха."], "Король не может остаться на первой горизонтали. Шагните на клетку вверх.", "Король покинул горизонталь ладьи. Остаться было бы нельзя."),
  mate: L("Мат", "Мат — это шах, из которого король не уходит, который нельзя закрыть и нельзя ответить взятием шахующей фигуры.", ["В отличие от обычного шаха, у другой стороны нет ни одного законного хода.", "Короля не снимают с доски. Партия кончается, ставившая мат сторона побеждает.", "Это детский мат: ферзь на h5, слон на c4 смотрит на f7.", "Возьмите ферзём пешку на f7."], "Нажмите ферзя на h5, затем f7.", "Ферзь на f7 защищён слоном с c4. Чёрный король не может его взять, закрыться или убежать."),
  draw: L("Ничья и пат", "Не каждый запертый король — это победа. Если у стороны нет хода и она не под шахом, это ничья — пат.", ["Ход чёрных. Король на a8 не под шахом, но a7, b7 и b8 контролирует белый ферзь. У чёрных нет хода.", "Это пат: ничья, а не поражение чёрных. Загнать короля в угол и забыть шах можно потерять выигранную партию.", "Ничья также при троекратном повторении, после 50 ходов без взятия и хода пешки, при недостатке материала или если принято предложение ничьей.", "Король против короля, король и конь или король и слон не могут форсировать мат."], "Эта позиция уже ничейная. Дальше — рокировка."),
  castle: L("Рокировка", "Рокировка — единственный ход, который двигает две фигуры сразу: король прячется в угол, ладья выходит.", ["Король идёт на две клетки к ладье. Ладья перепрыгивает короля и встаёт рядом.", "У белых короткая рокировка — вправо, на королевский фланг. Длинная — влево, на ферзевый.", "Можно, только если этот король и эта ладья не ходили, клетки между ними пусты, король не под шахом и не проходит и не встаёт на битую клетку.", "Каждая сторона рокируется один раз. Сделайте короткую: король с e1 на g1."], "Нажмите короля на e1, затем g1. Ладья с h1 сама прыгнет на f1.", "Король на g1, ладья на f1. Это один ход, не два."),
  passant: L("Взятие на проходе", "Если чужая пешка только что прыгнула на две клетки и встала рядом с вашей, её можно взять так, будто она прошла одну.", ["Чёрная пешка только что прыгнула с d7 на d5, рядом с белой на e5.", "Белые могут взять по диагонали на d6. Чёрная пешка на d5 исчезает, хотя вы встаёте на d6.", "Право действует только на ближайший ход. Любой другой ход его отнимает.", "Возьмите на проходе: пешка с e5 на d6."], "Нажмите белую пешку на e5, затем d6.", "Чёрная пешка взята, хотя её нет на клетке, куда вы пришли. Это единственное взятие мимо самой фигуры."),
  promote: L("Превращение", "Пешка на последней горизонтали больше не пешка. Её обязательно меняют на ферзя, ладью, слона или коня.", ["Белые превращаются на 8-й, чёрные на 1-й. Замена обязательна и происходит в том же ходе.", "Чаще выбирают ферзя: он ходит в больше сторон.", "Иногда сильнее конь, если его прыжок сразу даёт шах.", "Продвиньте пешку с e7 на e8 и превратите в ферзя."], "Нажмите пешку на e7, затем e8 и выберите ферзя.", "Пешка стала ферзём. Пешка на последней горизонтали часто меняет партию."),
};

const thL: Record<string, Copy> = {
  goal: L("เป้าหมาย", "หมากรุกคือการต่อสู้ของสองกองทัพบน 64 ช่อง ไม่ต้องกินทุกตัว แค่ทำให้คิงฝ่ายตรงข้ามไม่มีทางหนี", ["กระดานมีคอลัมน์ a–h และแถว 1–8 แต่ละฝ่ายเริ่มด้วยเบี้ย 8 เรือ 2 ม้า 2 บิชอป 2 ควีน 1 คิง 1", "ขาวเดินก่อน แล้วสลับกันฝ่ายละหนึ่งตา", "ชนะด้วยรุกจน: คิงถูกโจมตีและไม่มีตาที่ถูกกฎให้หนี", "คิงไม่ถูกกินออกจากกระดาน เกมหยุดเมื่อรุกจน", "เสมอได้เมื่อจนตาบอด ตำแหน่งซ้ำ หมากไม่พอ กฎ 50 ตา หรือตกลงกัน"], "อ่านจบแล้วไปบทถัดไป"),
  controls: L("วิธีเดิน", "บนกระดานนี้ หนึ่งตาคือสองครั้งแตะ: เลือกตัว แล้วเลือกช่อง", ["แตะตัวของฝ่ายที่จะเดิน ช่องที่ไปได้จะสว่าง", "จุดคือช่องว่าง วงแหวนคือตัวฝ่ายตรงข้าม แตะเพื่อกิน", "แตะตัวฝ่ายเดียวกันอีกตัวเพื่อเปลี่ยน แตะช่องที่ไปไม่ได้เพื่อยกเลิก", "ลากเพื่อหมุนมุม ลูกศรเลื่อนกล้อง + ซูมเข้าตัวที่เลือก − ซูมออก สี่เหลี่ยมเห็นทั้งกระดาน", "ลองเดินตาที่ถูกกฎของขาวสักตา"], "เลือกตัวขาว แล้วแตะช่องที่สว่าง", "ถูกต้อง ช่องสว่างคือตาที่ไปได้ ช่องไม่สว่างไปไม่ได้"),
  pawn: L("เบี้ย", "เบี้ยเดินช้าและไปข้างหน้าอย่างเดียว แต่เป็นตัวเดียวที่กินคนละทิศกับทางเดิน", ["เดินตรงหนึ่งช่องถ้าว่าง ถอยไม่ได้", "จากแถวเริ่มเดินได้สองช่องถ้าทั้งสองช่องข้างหน้าว่าง", "กินเฉียงไปข้างหน้าหนึ่งช่อง ไม่กินตรง", "ถึงแถวสุดท้ายต้องเลื่อนขั้น", "เบี้ยขาวอยู่ e4 จงกินเบี้ยดำที่ d5"], "แตะเบี้ยขาว แล้วแตะ d5", "เบี้ยกินเฉียง ถ้าเดินตรงไป e5 จะกินตัวที่อยู่เฉียงไม่ได้"),
  rook: L("เรือ", "เรือเดินตามแถวและคอลัมน์ ได้ไกลเท่าที่ต้องการถ้าทางว่าง", ["เดินแนวนอนหรือแนวตั้ง ไม่เฉียงและไม่กระโดด", "หยุดช่องว่าง หรือหยุดทับตัวศัตรูเพื่อกิน หยุดทับพวกเดียวกันไม่ได้", "เรือแข็งที่สุดบนคอลัมน์เปิด ที่ไม่มีเบี้ยทั้งสองฝ่าย", "พาเรือจาก a1 ขึ้นสุดคอลัมน์ a ถึง a8"], "แตะเรือที่ a1 แล้วแตะ a8", "เรือเดินตลอดคอลัมน์ a เพราะไม่มีตัวขวาง"),
  knight: L("ม้า", "ม้าเป็นตัวเดียวที่กระโดดข้ามตัวอื่น ทางเดินเป็นรูปตัว L เสมอ", ["สองช่องทางหนึ่งแล้วหนึ่งช่องตั้งฉาก หรือหนึ่งแล้วสอง", "กระโดดข้ามทั้งพวกและศัตรู ช่องปลายว่างคือเดิน มีศัตรูคือกิน", "ทุกตาเปลี่ยนสีช่อง จากช่องดำไปช่องขาว และกลับกัน", "พาม้าจาก b1 ไป c3"], "แตะม้าที่ b1 แล้วแตะ c3", "ขึ้นสองช่องแล้วขวาหนึ่งช่อง คือตัว L ม้าไม่ต้องมีทางว่าง"),
  bishop: L("บิชอป", "บิชอปเดินเฉียงอย่างเดียว และอยู่สีช่องเดิมตลอดเกม", ["เฉียงได้ไกลเท่าใดก็ได้ แต่ไม่กระโดด", "บิชอปที่เริ่มบนช่องดำไปช่องขาวไม่ได้ ดังนั้นบิชอปสองตัวของฝ่ายเดียวกันเฝ้าคนละสี", "บิชอปนี้อยู่ c1 ซึ่งเป็นช่องดำ g5 ก็เป็นช่องดำบนเส้นเฉียงเดียวกัน", "พาไป g5"], "แตะบิชอปที่ c1 แล้วแตะ g5", "บิชอปรักษาสีช่อง ไม่เคยเปลี่ยนไปช่องขาว"),
  queen: L("ควีน", "ควีนเดินได้ทั้งแบบเรือและบิชอป: แนวนอน แนวตั้ง หรือเฉียง", ["ได้ไกลเท่าใดก็ได้ แต่ไม่กระโดด", "ควีนแข็งที่สุดเพราะสลับสองทิศได้ เสียควีนมักเสียตำแหน่ง", "จาก d1 ควีนเดินตรงแบบเรือหรือเฉียงแบบบิชอปได้", "พาควีนตามเส้นเฉียงไป h5"], "แตะควีนที่ d1 แล้วแตะ h5", "เส้นเฉียงยาว ควีนจะเดินตรงไป d8 ก็ได้"),
  check: L("คิงและการรุก", "คิงเดินช้า ครั้งละหนึ่งช่อง และห้ามก้าวเข้าที่อันตราย", ["เดินหนึ่งช่องได้ทุกทิศ: แนวนอน แนวตั้ง หรือเฉียง", "ไปช่องที่ศัตรูคุมไม่ได้ และยืนติดคิงฝ่ายตรงข้ามไม่ได้", "รุกคือคิงถูกโจมตี ต้องหนีทันที: ย้ายคิง ขวาง หรือกินตัวที่รุก", "เรือดำรุกคิงขาวตามแถว 1 จงพาคิงออกจากการรุก"], "คิงอยู่แถว 1 ไม่ได้ ก้าวขึ้นหนึ่งช่อง", "คิงออกจากแถวที่เรือคุม ถ้าอยู่ต่อจะผิดกฎ"),
  mate: L("รุกจน", "รุกจนคือการรุกที่คิงหนีไม่ได้ ขวางไม่ได้ และกินตัวที่รุกไม่ได้", ["ต่างจากการรุกธรรมดา: ฝ่ายตรงข้ามไม่มีตาที่ถูกกฎเหลือเลย", "คิงไม่ถูกยกออกจากกระดาน เกมจบ ฝ่ายที่รุกจนเป็นผู้ชนะ", "นี่คือเมตของนักเรียน: ควีนอยู่ h5 บิชอปที่ c4 มอง f7", "ใช้ควีนกินเบี้ยที่ f7"], "แตะควีนที่ h5 แล้วแตะ f7", "ควีนบน f7 ได้รับการปกป้องจากบิชอป c4 คิงดำกินไม่ได้ ขวางไม่ได้ และไม่มีช่องหนี"),
  draw: L("เสมอและจนตาบอด", "ไม่ใช่คิงที่ติดทุกครั้งจะเป็นชนะ ถ้าฝ่ายที่จะเดินไม่มีตาที่ถูกกฎและไม่ถูกรุก เกมเสมอ เรียกว่าจนตาบอด", ["ถึงตาดำ คิงที่ a8 ไม่ถูกรุก แต่ a7 b7 และ b8 ถูกควีนขาวคุม ดำไม่มีตาเดิน", "นั่นคือจนตาบอด: เสมอ ไม่ใช่ดำแพ้ ไล่คิงเข้ามุมแต่ลืมรุกอาจทำเกมที่ชนะหลุดมือ", "เสมอยังเกิดเมื่อตำแหน่งเดิมซ้ำสามครั้ง เมื่อ 50 ตาไม่กินหมากและไม่เดินเบี้ย เมื่อหมากไม่พอรุกจน หรือเมื่อขอเสมอแล้วได้รับ", "คิงกับคิง คิงกับม้าหนึ่ง หรือคิงกับบิชอปหนึ่ง บังคับรุกจนไม่ได้"], "ตำแหน่งนี้เสมอแล้ว บทหน้าเรียนการเข้าป้อม"),
  castle: L("เข้าป้อม", "เข้าป้อมเป็นตาเดียวที่เดินสองตัวพร้อมกัน: คิงหลบเข้ามุม เรือออกมา", ["คิงเดินสองช่องเข้าหาเรือ เรือกระโดดข้ามคิงไปยืนช่องติดคิง", "ของขาว ด้านขวาคือเข้าป้อมสั้น ด้านซ้ายคือเข้าป้อมยาว", "ทำได้เมื่อคิงและเรือนั้นยังไม่เคยเดิน ช่องระหว่างว่าง คิงไม่ถูกรุก และคิงไม่ผ่านหรือหยุดบนช่องที่ถูกโจมตี", "แต่ละฝ่ายเข้าป้อมได้ครั้งเดียว จงเข้าป้อมคิง: พาคิงจาก e1 ไป g1"], "แตะคิงที่ e1 แล้วแตะ g1 เรือ h1 จะกระโดดไป f1 เอง", "คิงไป g1 เรือไป f1 นี่คือหนึ่งตา ไม่ใช่สองตา"),
  passant: L("กินผ่าน", "ถ้าเบี้ยศัตรูเพิ่งกระโดดสองช่องแล้วหยุดข้างเบี้ยคุณ คุณกินมันได้ราวกับมันเดินแค่ช่องเดียว", ["เบี้ยดำเพิ่งกระโดดจาก d7 มา d5 ขนานกับเบี้ยขาวที่ e5", "ขาวกินเฉียงไป d6 ได้ เบี้ยดำที่ d5 หายไป แม้คุณจะไปลงที่ d6", "สิทธิ์นี้มีแค่ตาถัดไปทันที เดินตาอื่นคือเสียสิทธิ์", "จงกินผ่าน: เบี้ย e5 ไป d6"], "แตะเบี้ยขาวที่ e5 แล้วแตะ d6", "เบี้ยดำถูกกินทั้งที่ไม่ได้อยู่ช่องที่คุณไปลง นี่เป็นตาเดียวที่กินแล้วไม่ลงทับตัวที่ถูกกิน"),
  promote: L("เลื่อนขั้น", "เบี้ยที่ถึงแถวสุดท้ายไม่ใช่เบี้ยอีกต่อไป คุณต้องเปลี่ยนเป็นควีน เรือ บิชอป หรือม้า", ["ขาวเลื่อนที่แถว 8 ดำเลื่อนที่แถว 1 การเปลี่ยนบังคับและเกิดในตาเดียวกัน", "ส่วนใหญ่ควรเลือกควีน เพราะเดินได้หลายทิศที่สุด", "บางครั้งเลื่อนเป็นม้าแข็งกว่า ถ้าการกระโดดของม้ารุกคิงทันที", "ดันเบี้ย e7 ขึ้น e8 แล้วเลื่อนเป็นควีน"], "แตะเบี้ยที่ e7 แตะ e8 แล้วเลือกควีน", "เบี้ยกลายเป็นควีน เบี้ยถึงแถวสุดท้ายมักเปลี่ยนทั้งเกม"),
};

const idL: Record<string, Copy> = {
  goal: L("Tujuan", "Catur adalah pertarungan dua pasukan di 64 kotak. Tidak perlu memakan semua bidak — cukup buat raja lawan tidak punya jalan keluar.", ["Papan punya lajur a–h dan baris 1–8. Masing-masing mulai dengan 8 pion, 2 benteng, 2 kuda, 2 gajah, 1 menteri, dan 1 raja.", "Putih jalan dulu, lalu bergiliran satu langkah.", "Menang dengan skakmat: raja lawan diserang dan tidak ada langkah sah untuk lolos.", "Raja tidak pernah dimakan. Permainan berhenti saat skakmat.", "Remis terjadi karena stalemate, pengulangan, materi kurang, aturan 50 langkah, atau kesepakatan."], "Setelah membaca, lanjut ke pelajaran berikutnya."),
  controls: L("Cara berjalan", "Di papan ini satu langkah adalah dua ketukan: pilih bidak, lalu pilih kotak.", ["Ketuk bidak pihak yang giliran. Kotak yang sah menyala.", "Titik adalah kotak kosong. Cincin adalah bidak lawan — ketuk untuk memakannya.", "Ketuk bidak kawan lain untuk ganti pilihan. Kotak yang tidak sah membatalkan.", "Seret untuk memutar. Panah menggeser kamera. + memperbesar bidak terpilih, − menjauh, kotak menampilkan seluruh papan.", "Coba langkah sah apa pun untuk Putih."], "Pilih bidak putih, lalu ketuk kotak yang menyala.", "Benar. Kotak menyala itu sah. Yang tidak menyala tidak bisa dicapai."),
  pawn: L("Pion", "Pion lambat dan hanya maju, tetapi satu-satunya bidak yang memakan ke arah berbeda dari arah berjalannya.", ["Maju satu kotak lurus jika kosong. Tidak bisa mundur.", "Dari baris awal boleh maju dua kotak jika kedua kotak di depan kosong.", "Memakan satu kotak diagonal ke depan, tidak pernah lurus.", "Di baris terakhir wajib dipromosikan.", "Pion putih ada di e4. Makan pion hitam di d5."], "Ketuk pion putih, lalu d5.", "Pion memakan diagonal. Maju lurus ke e5 tidak memakan bidak di diagonal."),
  rook: L("Benteng", "Benteng berjalan sepanjang baris dan lajur, sejauh apa pun jika jalannya bersih.", ["Mendatar atau tegak, tidak diagonal, dan tidak melompat.", "Boleh berhenti di kotak kosong atau di atas bidak lawan untuk memakannya. Tidak boleh di atas kawan.", "Paling kuat di lajur terbuka — lajur tanpa pion kedua pihak.", "Bawa benteng dari a1 sampai ujung lajur a, ke a8."], "Ketuk benteng di a1, lalu a8.", "Benteng menempuh seluruh lajur a karena tidak ada yang menghalangi."),
  knight: L("Kuda", "Kuda adalah satu-satunya bidak yang melompat. Langkahnya selalu bentuk L.", ["Dua kotak ke satu arah lalu satu ke samping. Atau satu lalu dua.", "Melompati kawan dan lawan. Tujuan kosong berarti jalan; ada lawan berarti makan.", "Setiap langkah mengubah warna kotak: dari gelap ke terang, dan sebaliknya.", "Bawa kuda dari b1 ke c3."], "Ketuk kuda di b1, lalu c3.", "Dua ke atas dan satu ke kanan — itulah L. Kuda tidak perlu jalan kosong."),
  bishop: L("Gajah", "Gajah hanya berjalan diagonal dan tetap di satu warna kotak sepanjang permainan.", ["Boleh sejauh apa pun secara diagonal, tetapi tidak melompat.", "Gajah yang mulai di kotak gelap tidak pernah sampai ke kotak terang. Jadi dua gajah satu pihak mengawasi warna berbeda.", "Gajah ini di c1, kotak gelap. g5 juga gelap, pada diagonal yang sama.", "Bawa ke g5."], "Ketuk gajah di c1, lalu g5.", "Gajah mempertahankan warna kotaknya. Ia tidak pernah pindah ke kotak terang."),
  queen: L("Menteri", "Menteri berjalan seperti benteng dan gajah sekaligus: mendatar, tegak, atau diagonal.", ["Sejauh apa pun, tetapi tidak melompat.", "Ini bidak terkuat karena bisa berganti kedua arah. Kehilangannya biasanya kehilangan posisi.", "Dari d1 menteri bisa tegak seperti benteng atau diagonal seperti gajah.", "Bawa lewat diagonal ke h5."], "Ketuk menteri di d1, lalu h5.", "Diagonal yang panjang. Ia juga bisa lurus ke d8."),
  check: L("Raja dan skak", "Raja berjalan pelan, hanya satu kotak, dan tidak boleh masuk ke bahaya.", ["Satu kotak ke segala arah: mendatar, tegak, atau diagonal.", "Tidak boleh ke kotak yang diserang lawan, dan tidak boleh berdiri di samping raja lawan.", "Skak berarti raja sedang diserang. Harus segera lolos: pindahkan raja, halangi garis, atau makan bidak yang menyekak.", "Benteng hitam menyekak raja putih di baris 1. Keluarkan raja dari skak."], "Raja tidak boleh tetap di baris 1. Naik satu kotak.", "Raja meninggalkan baris yang dikuasai benteng. Tetap di sana adalah ilegal."),
  mate: L("Skakmat", "Skakmat adalah skak yang rajanya tidak bisa pergi, tidak bisa dihalangi, dan bidak penyekaknya tidak bisa dimakan.", ["Berbeda dari skak biasa: lawan tidak punya langkah sah sama sekali.", "Raja tidak diangkat dari papan. Permainan berakhir dan pihak yang mat menang.", "Ini mate gembala: menteri di h5, gajah di c4 memandang f7.", "Makan pion di f7 dengan menteri."], "Ketuk menteri di h5, lalu f7.", "Menteri di f7 dilindungi gajah c4. Raja hitam tidak bisa memakannya, menghalangi, atau kabur."),
  draw: L("Remis dan stalemate", "Tidak setiap raja yang terjebak adalah kemenangan. Jika pihak yang giliran tidak punya langkah sah dan tidak skak, itu remis — stalemate.", ["Giliran Hitam. Raja di a8 tidak skak, tetapi a7, b7, dan b8 dikuasai menteri putih. Hitam tidak punya langkah.", "Itu stalemate: remis, bukan kekalahan Hitam. Mengurung raja di sudut tanpa memberi skak bisa membuang kemenangan.", "Remis juga terjadi jika posisi yang sama berulang tiga kali, setelah 50 langkah tanpa makan atau langkah pion, jika materi tidak cukup untuk mat, atau jika tawaran remis diterima.", "Raja lawan raja, raja dan kuda, atau raja dan gajah tidak bisa memaksa skakmat."], "Posisi ini sudah remis. Lanjut untuk belajar rokade."),
  castle: L("Rokade", "Rokade adalah satu-satunya langkah yang menggerakkan dua bidak sekaligus: raja bersembunyi di sudut dan benteng keluar.", ["Raja berjalan dua kotak ke arah benteng. Benteng melompati raja dan berdiri di kotak di sampingnya.", "Bagi Putih, sayap raja di kanan adalah rokade pendek. Sayap menteri di kiri adalah rokade panjang.", "Hanya boleh jika raja dan benteng itu belum bergerak, kotak di antaranya kosong, raja tidak sedang skak, dan raja tidak melewati atau berhenti di kotak yang diserang.", "Setiap pihak rokade hanya sekali. Rokade pendek: bawa raja dari e1 ke g1."], "Ketuk raja di e1, lalu g1. Benteng h1 akan melompat sendiri ke f1.", "Raja ke g1, benteng ke f1. Itu satu langkah, bukan dua."),
  passant: L("En passant", "Jika pion lawan baru melompat dua kotak dan berhenti di samping pionmu, kamu boleh memakannya seolah ia hanya maju satu.", ["Pion hitam baru melompat dari d7 ke d5, sejajar dengan pion putih di e5.", "Putih boleh makan diagonal ke d6. Pion hitam di d5 hilang, meski kamu mendarat di d6.", "Hak ini hanya untuk langkah berikutnya. Langkah lain menghilangkan hak itu.", "Makan en passant: pion e5 ke d6."], "Ketuk pion putih di e5, lalu d6.", "Pion hitam dimakan meski tidak berdiri di kotak tujuanmu. Ini satu-satunya tangkapan yang tidak mendarat di bidak yang dimakan."),
  promote: L("Promosi", "Pion yang sampai baris terakhir bukan pion lagi. Kamu harus mengubahnya menjadi menteri, benteng, gajah, atau kuda.", ["Putih promosi di baris 8. Hitam di baris 1. Perubahan wajib dan terjadi pada langkah yang sama.", "Biasanya pilih menteri karena menjangkau paling banyak arah.", "Kadang kuda lebih kuat jika lompatannya langsung menyekak raja lawan.", "Dorong pion e7 ke e8 dan promosikan menjadi menteri."], "Ketuk pion di e7, ketuk e8, lalu pilih Menteri.", "Pion menjadi menteri. Pion di baris terakhir sering mengubah seluruh permainan."),
};

const hiL: Record<string, Copy> = {
  goal: L("लक्ष्य", "शतरंज 64 खानों पर दो सेनाओं की लड़ाई है। हर मोहरा खाने की ज़रूरत नहीं — दुश्मन के राजा के पास कोई रास्ता न बचे।", ["बोर्ड में a–h स्तंभ और 1–8 पंक्तियाँ हैं। हर ओर 8 प्यादे, 2 हाथी, 2 घोड़े, 2 ऊँट, 1 रानी और 1 राजा से शुरुआत।", "सफ़ेद पहले चलता है, फिर बारी-बारी एक चाल।", "जीत शह और मात से होती है: राजा पर हमला है और कोई वैध चाल नहीं बचाती।", "राजा कभी खाया नहीं जाता। मात पर खेल रुक जाता है।", "गतिरोध, दोहराव, कम मोहरें, 50 चाल या सहमति से ड्रॉ होता है।"], "पढ़ लेने पर अगला पाठ खोलें।"),
  controls: L("कैसे चलें", "इस बोर्ड पर एक चाल दो छुअन है: मोहरा चुनें, फिर खाना चुनें।", ["जिसकी बारी हो उसका मोहरा छुएँ। वैध खाने जलेंगे।", "बिंदु खाली खाना है। छल्ला दुश्मन का मोहरा है — खाने के लिए छुएँ।", "दूसरा अपना मोहरा चुनाव बदलता है। अवैध खाना रद्द करता है।", "घुमाने के लिए खींचें। तीर कैमरा हिलाते हैं। + चुने मोहरे के पास, − दूर, वर्ग पूरा बोर्ड।", "सफ़ेद की कोई भी वैध चाल आज़माएँ।"], "एक सफ़ेद मोहरा चुनें, फिर जलता खाना छुएँ।", "सही। जलता खाना वैध है। बिना जले खाने तक नहीं पहुँचा जा सकता।"),
  pawn: L("प्यादा", "प्यादा धीमा है और केवल आगे बढ़ता है, पर वही अकेला मोहरा है जो चलने से अलग दिशा में खाता है।", ["आगे का खाना खाली हो तो एक खाना सीधा। पीछे नहीं।", "शुरुआती पंक्ति से दो खाने, अगर दोनों आगे खाली हों।", "तिरछा एक खाना आगे खाता है, कभी सीधा नहीं।", "आखिरी पंक्ति पर पदोन्नति ज़रूरी है।", "सफ़ेद प्यादा e4 पर है। d5 का काला प्यादा खाएँ।"], "सफ़ेद प्यादा छुएँ, फिर d5।", "प्यादा तिरछा खाता है। सीधा e5 जाने से तिरछा मोहरा नहीं खिलेगा।"),
  rook: L("हाथी", "हाथी पंक्ति और स्तंभ पर जितना चाहे चलता है, जब रास्ता साफ़ हो।", ["आड़ा या सीधा, तिरछा नहीं, और कूदता नहीं।", "खाली खाने पर रुके या दुश्मन पर खड़ा होकर खाए। अपने पर नहीं।", "खुले स्तंभ पर सबसे मज़बूत — जहाँ दोनों ओर के प्यादे न हों।", "हाथी को a1 से स्तंभ a के अंत a8 तक ले जाएँ।"], "a1 का हाथी छुएँ, फिर a8।", "स्तंभ a पूरे का पूरा खुला है क्योंकि बीच में कोई नहीं।"),
  knight: L("घोड़ा", "घोड़ा ही अकेला मोहरा है जो कूदता है। उसकी चाल हमेशा L होती है।", ["एक दिशा में दो खाने, फिर एक बगल में। या एक फिर दो।", "अपने और दुश्मन दोनों के ऊपर कूदता है। खाली गंतव्य चाल है, दुश्मन हो तो खाना।", "हर चाल खाने का रंग बदलती है: काले से सफ़ेद, और उलटा।", "घोड़े को b1 से c3 ले जाएँ।"], "b1 का घोड़ा छुएँ, फिर c3।", "दो ऊपर और एक दाएँ — यही L है। घोड़े को साफ़ रास्ता नहीं चाहिए।"),
  bishop: L("ऊँट", "ऊँट केवल तिरछा चलता है और पूरे खेल एक ही रंग के खाने पर रहता है।", ["तिरछा जितना चाहे, पर कूदता नहीं।", "काले खाने से शुरू ऊँट सफ़ेद खाने तक कभी नहीं पहुँचता। इसलिए एक ओर के दो ऊँट अलग रंग देखते हैं।", "यह ऊँट c1 पर है, काला खाना। g5 भी काला है, उसी विकर्ण पर।", "इसे g5 ले जाएँ।"], "c1 का ऊँट छुएँ, फिर g5।", "ऊँट ने अपना रंग रखा। वह सफ़ेद खाने पर नहीं जाता।"),
  queen: L("रानी", "रानी हाथी और ऊँट दोनों की तरह चलती है: आड़ा, सीधा या तिरछा।", ["जितना चाहे, पर कूदती नहीं।", "वह सबसे मज़बूत है क्योंकि दोनों दिशाएँ बदल सकती है। उसे खोना अक्सर स्थिति खोना है।", "d1 से रानी हाथी की तरह स्तंभ पर या ऊँट की तरह विकर्ण पर जा सकती है।", "विकर्ण से h5 ले जाएँ।"], "d1 की रानी छुएँ, फिर h5।", "लंबा विकर्ण। वह सीधा d8 भी जा सकती थी।"),
  check: L("राजा और शह", "राजा धीमा है, एक बार में एक खाना, और खतरे में नहीं कदम रख सकता।", ["हर दिशा में एक खाना: आड़ा, सीधा या तिरछा।", "दुश्मन के हमले वाले खाने पर नहीं, और दुश्मन के राजा के बगल नहीं।", "शह का मतलब राजा पर हमला है। तुरंत बचें: राजा हटाएँ, रास्ता रोकें, या शह देने वाला खाएँ।", "काला हाथी पहली पंक्ति पर सफ़ेद राजा को शह दे रहा है। राजा को शह से निकालें।"], "राजा पहली पंक्ति पर नहीं रह सकता। एक खाना ऊपर बढ़ें।", "राजा उस पंक्ति से निकला जिसे हाथी नियंत्रित करता है। वहीं रहना अवैध होता।"),
  mate: L("शह और मात", "मात वह शह है जिससे राजा निकल नहीं सकता, रोका नहीं जा सकता, और शह देने वाला मोहरा खाया नहीं जा सकता।", ["साधारण शह से अलग: दूसरी ओर के पास कोई वैध चाल नहीं बचती।", "राजा बोर्ड से नहीं हटाया जाता। खेल खत्म, मात देने वाला जीतता है।", "यह विद्वान की मात है: रानी h5 पर, ऊँट c4 से f7 देखता है।", "रानी से f7 का प्यादा खाएँ।"], "h5 की रानी छुएँ, फिर f7।", "f7 की रानी को c4 का ऊँट बचाता है। काला राजा उसे खा नहीं सकता, रोक नहीं सकता, और भागने का खाना नहीं है।"),
  draw: L("ड्रॉ और गतिरोध", "हर फँसा राजा जीत नहीं होता। यदि बारी वाले के पास कोई वैध चाल नहीं और शह भी नहीं, तो ड्रॉ है — गतिरोध।", ["काले की बारी। a8 का राजा शह में नहीं, पर a7, b7 और b8 सफ़ेद रानी के नियंत्रण में हैं। काले के पास चाल नहीं।", "यह गतिरोध है: ड्रॉ, काले की हार नहीं। राजा को कोने में धकेलकर शह देना भूल जाएँ तो जीती बाज़ी छिन सकती है।", "ड्रॉ तब भी जब वही स्थिति तीन बार आए, 50 चाल बिना खाने या प्यादे के, मात के लिए मोहरें कम हों, या ड्रॉ मान लिया जाए।", "राजा बनाम राजा, राजा और घोड़ा, या राजा और ऊँट मात नहीं जबरदस्ती कर सकते।"], "यह स्थिति पहले से ड्रॉ है। आगे किला सीखें।"),
  castle: L("किला", "किला वह अकेली चाल है जिसमें दो मोहरे एक साथ चलते हैं: राजा कोने में छिपता है और हाथी बाहर आता है।", ["राजा हाथी की ओर दो खाने चलता है। हाथी राजा के ऊपर से कूदकर उसके बगल खड़े होता है।", "सफ़ेद के लिए दाएँ राजा-पक्ष छोटा किला है। बाएँ रानी-पक्ष लंबा किला।", "तभी जब वह राजा और हाथी न चले हों, बीच के खाने खाली हों, राजा शह में न हो, और राजा हमले वाले खाने से न गुज़रे न रुके।", "हर ओर केवल एक बार। राजा-पक्ष का किला: राजा को e1 से g1 ले जाएँ।"], "e1 का राजा छुएँ, फिर g1। h1 का हाथी अपने आप f1 कूदेगा।", "राजा g1, हाथी f1। यह एक चाल है, दो नहीं।"),
  passant: L("एन पासंत", "यदि दुश्मन का प्यादा अभी दो खाने कूदा है और आपके प्यादे के बगल रुका है, तो उसे ऐसे खा सकते हैं जैसे वह एक ही खाना चला हो।", ["काला प्यादा अभी d7 से d5 कूदा, e5 के सफ़ेद प्यादे के बराबर।", "सफ़ेद तिरछा d6 खा सकता है। d5 का काला प्यादा गायब होता है, भले आप d6 पर पहुँचें।", "यह अधिकार केवल अगली चाल तक है। कोई और चाल इसे खो देती है।", "एन पासंत खाएँ: e5 का प्यादा d6 जाए।"], "e5 का सफ़ेद प्यादा छुएँ, फिर d6।", "काला प्यादा खा लिया गया भले वह उस खाने पर न हो जहाँ आप पहुँचे। यही अकेली खान है जो खाए मोहरे पर नहीं ठहरती।"),
  promote: L("पदोन्नति", "आखिरी पंक्ति पहुँचा प्यादा प्यादा नहीं रहता। उसे रानी, हाथी, ऊँट या घोड़ा बनाना ज़रूरी है।", ["सफ़ेद 8वीं पंक्ति पर, काला 1ली पर। बदलाव ज़रूरी है और उसी चाल में होता है।", "अक्सर रानी चुनें, क्योंकि वह सबसे अधिक दिशाएँ कवर करती है।", "कभी घोड़ा बेहतर होता है, यदि उसकी छलांग तुरंत शह दे।", "प्यादे को e7 से e8 बढ़ाएँ और रानी बनाएँ।"], "e7 का प्यादा छुएँ, e8 छुएँ, फिर रानी चुनें।", "प्यादा रानी बन गया। आखिरी पंक्ति का प्यादा अक्सर पूरी बाज़ी बदल देता है।"),
};

const arL: Record<string, Copy> = {
  goal: L("الهدف", "الشطرنج قتال بين جيشين على 64 مربعًا. لا حاجة لأكل كل القطع — يكفي ألا يبقى للملك الخصم مهرب.", ["للرقعة أعمدة a–h وصفوف 1–8. يبدأ كل طرف بـ 8 بيادق وقلعتين وحصانين وفيلين ووزير وملك.", "الأبيض يبدأ، ثم يتناوب الطرفان نقلة واحدة.", "الفوز بالكش مات: الملك مُهاجَم ولا نقلة قانونية تنقذه.", "الملك لا يُؤخذ أبدًا. تتوقف المباراة عند المات.", "التعادل بالطريق المسدود أو التكرار أو نقص القوة أو قاعدة الخمسين أو الاتفاق."], "بعد القراءة انتقل إلى الدرس التالي."),
  controls: L("كيف تلعب", "على هذه الرقعة النقلة لمستان: اختر قطعة ثم اختر مربعًا.", ["المس قطعة الطرف الذي عليه الدور. المربعات القانونية تضيء.", "النقطة مربع فارغ. الحلقة قطعة عدو — المسها لتأخذها.", "قطعة أخرى من طرفك تغيّر الاختيار. مربع غير قانوني يلغي.", "اسحب لتدوير المنظور. الأسهم تحرّك الكاميرا. + يقرّب القطعة المختارة، − يبعّد، والمربع يُظهر الرقعة كلها.", "جرّب أي نقلة قانونية للأبيض."], "اختر قطعة بيضاء ثم المس مربعًا مضاءً.", "صحيح. المربع المضاء قانوني، وغير المضاء لا يُبلغ."),
  pawn: L("البيدق", "البيدق بطيء ويتقدم فقط، وهو القطعة الوحيدة التي تأخذ في اتجاه مختلف عن اتجاه سيرها.", ["يتقدم مربعًا واحدًا إلى الأمام إن كان فارغًا. لا يرجع.", "من صف البداية يجوز مربعان إذا كان المربعان أمامه فارغين.", "يأخذ مربعًا واحدًا قُطرًا إلى الأمام، لا أبدًا إلى الأمام مباشرة.", "في الصف الأخير يجب ترقيته.", "البيدق الأبيض في e4. خذ البيدق الأسود في d5."], "المس البيدق الأبيض ثم d5.", "البيدق يأخذ قُطرًا. التقدم مباشرة إلى e5 لا يأكل القطعة على القطر."),
  rook: L("القلعة", "تسير القلعة على الصفوف والأعمدة أي مسافة إذا كان الطريق خاليًا.", ["أفقيًا أو عموديًا، لا قُطرًا، ولا تقفز.", "تقف على مربع فارغ أو على قطعة عدو لتأخذها. لا تقف على قطعة صديقة.", "أقوى ما تكون على عمود مفتوح بلا بيادق من الطرفين.", "انقل القلعة من a1 حتى نهاية العمود a إلى a8."], "المس القلعة في a1 ثم a8.", "تعبر القلعة العمود a كله لأن لا أحد يقف بينهما."),
  knight: L("الحصان", "الحصان هو القطعة الوحيدة التي تقفز. نقلته دائمًا على شكل L.", ["مربعان في اتجاه ثم مربع جانبي. أو مربع ثم مربعان.", "يقفز فوق الأصدقاء والأعداء. الوجهة الفارغة نقلة، والعدو هناك أخذ.", "كل نقلة تغيّر لون مربعه: من الداكن إلى الفاتح والعكس.", "انقل الحصان من b1 إلى c3."], "المس الحصان في b1 ثم c3.", "مربعان للأعلى وواحد لليمين — تلك هي L. الحصان لا يحتاج طريقًا خاليًا."),
  bishop: L("الفيل", "يتحرك الفيل قُطرًا فقط ويبقى على لون مربع واحد طوال المباراة.", ["أي مسافة قُطرًا، لكنه لا يقفز.", "فيل يبدأ على مربع داكن لا يبلغ مربعًا فاتحًا أبدًا. لذلك فيلا الطرف يراقبان لونين مختلفين.", "هذا الفيل في c1، مربع داكن. g5 داكن أيضًا وعلى القطر نفسه.", "انقله إلى g5."], "المس الفيل في c1 ثم g5.", "حافظ الفيل على لون مربعه. لا ينتقل أبدًا إلى مربع فاتح."),
  queen: L("الوزير", "يتحرك الوزير كالقلعة والفيل معًا: أفقيًا أو عموديًا أو قُطرًا.", ["أي مسافة، لكنه لا يقفز.", "هو أقوى قطعة لأنه يبدّل الاتجاهين. فقدانه غالبًا يفقد الوضع.", "من d1 يستطيع السير كالقلعة على العمود أو كالفيل على القطر.", "سر به على القطر إلى h5."], "المس الوزير في d1 ثم h5.", "قطر طويل. كان يستطيع أيضًا السير مباشرة إلى d8."),
  check: L("الملك والكش", "الملك بطيء، مربع واحد في كل مرة، ولا يجوز أن يخطو إلى الخطر.", ["مربع واحد في أي اتجاه: أفقي أو عمودي أو قطري.", "لا يجوز مربعًا يهاجمه العدو، ولا الوقوف بجانب ملك العدو.", "الكش يعني أن الملك مُهاجَم. يجب الخروج فورًا: حرّك الملك أو سد الخط أو خذ القطعة التي تكش.", "القلعة السوداء تكش الملك الأبيض على الصف 1. أخرج الملك من الكش."], "لا يجوز أن يبقى الملك على الصف 1. اصعد مربعًا.", "غادر الملك الصف الذي تسيطر عليه القلعة. البقاء هناك غير قانوني."),
  mate: L("كش مات", "الكش مات كش لا يستطيع الملك مغادرته ولا سدّه ولا أخذ القطعة التي تكش.", ["بخلاف الكش العادي، لا تبقى للخصم أي نقلة قانونية.", "لا يُرفع الملك عن الرقعة. تنتهي المباراة ويفوز من وضع المات.", "هذه ماتة التلميذ: الوزير في h5 والفيل في c4 ينظر إلى f7.", "خذ البيدق في f7 بالوزير."], "المس الوزير في h5 ثم f7.", "الوزير في f7 يحميه الفيل في c4. الملك الأسود لا يأخذه ولا يسد ولا يجد مربع فرار."),
  draw: L("التعادل والطريق المسدود", "ليس كل ملك محاصر فوزًا. إذا لم يكن لمن عليه الدور نقلة قانونية ولم يكن في كش، فالمباراة تعادل — طريق مسدود.", ["دور الأسود. الملك في a8 ليس في كش، لكن a7 وb7 وb8 يسيطر عليها الوزير الأبيض. لا نقلة للأسود.", "هذا طريق مسدود: تعادل لا خسارة للأسود. دفع الملك إلى الزاوية من دون كش قد يضيّع فوزًا.", "يقع التعادل أيضًا إذا تكرر الوضع ثلاث مرات، أو بعد 50 نقلة بلا أخذ ولا تحريك بيدق، أو إذا لم تكفِ القوة للمات، أو إذا قُبل طلب التعادل.", "ملك ضد ملك، أو ملك وحصان، أو ملك وفيل لا يفرضون المات."], "هذا الوضع متعادل بالفعل. تابع لتعلم التبييت."),
  castle: L("التبييت", "التبييت النقلة الوحيدة التي تحرّك قطعتين معًا: يختبئ الملك في الزاوية وتخرج قلعة.", ["يتحرك الملك مربعَين نحو قلعة. تقفز القلعة فوق الملك وتقف في المربع المجاور له.", "للأبيض، جانب الملك على اليمين تبييت قصير. جانب الوزير على اليسار تبييت طويل.", "يجوز فقط إذا لم يتحرك ذلك الملك وتلك القلعة، والمربعات بينهما فارغة، والملك ليس في كش، ولا يمر ولا يقف على مربع مُهاجَم.", "كل طرف يبيّت مرة واحدة. بيّت قصيرًا: انقل الملك من e1 إلى g1."], "المس الملك في e1 ثم g1. قلعة h1 تقفز وحدها إلى f1.", "الملك إلى g1 والقلعة إلى f1. هذه نقلة واحدة لا اثنتان."),
  passant: L("الأخذ بالتجاوز", "إذا قفز بيدق العدو للتو مربعَين ووقف بجانب بيدقك، يجوز أخذه كأنما تقدم مربعًا واحدًا.", ["قفز البيدق الأسود للتو من d7 إلى d5، بجانب البيدق الأبيض في e5.", "يجوز للأبيض الأخذ قُطرًا إلى d6. يختفي البيدق الأسود في d5 وإن هبطت في d6.", "هذا الحق للنقلة التالية مباشرة فقط. أي نقلة أخرى تُضيعه.", "خذ بالتجاوز: البيدق في e5 إلى d6."], "المس البيدق الأبيض في e5 ثم d6.", "يُؤخذ البيدق الأسود وإن لم يقف على المربع الذي وصلت إليه. هذا الأخذ الوحيد الذي لا يهبط على القطعة المأخوذة."),
  promote: L("الترقية", "البيدق الذي يبلغ الصف الأخير لم يعد بيدقًا. يجب تحويله إلى وزير أو قلعة أو فيل أو حصان.", ["الأبيض يرقّي في الصف 8 والأسود في الصف 1. التغيير واجب ويحدث في النقلة نفسها.", "في أغلب الأحيان اختر الوزير لأنه يغطي أكثر الاتجاهات.", "أحيانًا الحصان أقوى إذا كانت قفزته تكش الملك فورًا.", "ادفع البيدق من e7 إلى e8 ورقِّه إلى وزير."], "المس البيدق في e7 ثم e8 ثم اختر الوزير.", "صار البيدق وزيرًا. بيدق في الصف الأخير كثيرًا ما يغيّر المباراة كلها."),
};

packs.fr = fr;
packs.de = de;
packs.pt = pt;
packs.ru = ru;
packs.th = thL;
packs.id = idL;
packs.hi = hiL;
packs.ar = arL;

export function localizeLesson(lang: Lang, lesson: Lesson): Lesson {
  const copy = lang === "vi" ? undefined : packs[lang]?.[lesson.id];
  if (!copy) return lesson;
  return { ...lesson, title: copy.title, lead: copy.lead, points: copy.points, hint: copy.hint, success: copy.success };
}
